domain_path: C:\Users\monde\Documents\GitHub\nasa-CPU\Vitis_workspace\platform_rv32i_npp_ip\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
