// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rv32i_npp_ip_rv32i_npp_ip,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.443000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=256,HLS_SYN_DSP=0,HLS_SYN_FF=4071,HLS_SYN_LUT=3645,HLS_VERSION=2023_1}" *)

module rv32i_npp_ip (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 20;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] start_pc;
wire   [15:0] code_ram_address0;
reg    code_ram_ce0;
wire   [31:0] code_ram_q0;
reg   [15:0] data_ram_address0;
reg    data_ram_ce0;
reg   [3:0] data_ram_we0;
reg   [31:0] data_ram_d0;
wire   [31:0] data_ram_q0;
reg    nb_instruction_ap_vld;
wire   [31:0] grp_fu_663_p2;
reg   [31:0] reg_711;
wire    ap_CS_fsm_state4;
wire   [2:0] ap_phi_mux_d_i_type_phi_fu_468_p50;
reg   [0:0] d_i_is_jalr_reg_2723;
reg   [0:0] d_i_is_load_reg_2715;
reg   [15:0] pc_2_reg_2452;
wire    ap_CS_fsm_state2;
reg   [31:0] reg_file_1_load_load_fu_896_p1;
reg   [31:0] reg_file_1_load_reg_2464;
wire    ap_CS_fsm_state3;
reg   [31:0] reg_file_2_load_load_fu_899_p1;
reg   [31:0] reg_file_2_load_reg_2470;
reg   [31:0] reg_file_3_load_load_fu_902_p1;
reg   [31:0] reg_file_3_load_reg_2476;
reg   [31:0] reg_file_4_load_load_fu_905_p1;
reg   [31:0] reg_file_4_load_reg_2482;
reg   [31:0] reg_file_5_load_load_fu_908_p1;
reg   [31:0] reg_file_5_load_reg_2488;
reg   [31:0] reg_file_6_load_load_fu_911_p1;
reg   [31:0] reg_file_6_load_reg_2494;
reg   [31:0] reg_file_7_load_load_fu_914_p1;
reg   [31:0] reg_file_7_load_reg_2500;
reg   [31:0] reg_file_8_load_load_fu_917_p1;
reg   [31:0] reg_file_8_load_reg_2506;
reg   [31:0] reg_file_9_load_load_fu_920_p1;
reg   [31:0] reg_file_9_load_reg_2512;
reg   [31:0] reg_file_10_load_load_fu_923_p1;
reg   [31:0] reg_file_10_load_reg_2518;
reg   [31:0] reg_file_11_load_load_fu_926_p1;
reg   [31:0] reg_file_11_load_reg_2524;
reg   [31:0] reg_file_12_load_load_fu_929_p1;
reg   [31:0] reg_file_12_load_reg_2530;
reg   [31:0] reg_file_13_load_load_fu_932_p1;
reg   [31:0] reg_file_13_load_reg_2536;
reg   [31:0] reg_file_14_load_load_fu_935_p1;
reg   [31:0] reg_file_14_load_reg_2542;
reg   [31:0] reg_file_15_load_load_fu_938_p1;
reg   [31:0] reg_file_15_load_reg_2548;
reg   [31:0] reg_file_16_load_load_fu_941_p1;
reg   [31:0] reg_file_16_load_reg_2554;
reg   [31:0] reg_file_17_load_load_fu_944_p1;
reg   [31:0] reg_file_17_load_reg_2560;
reg   [31:0] reg_file_18_load_load_fu_947_p1;
reg   [31:0] reg_file_18_load_reg_2566;
reg   [31:0] reg_file_19_load_load_fu_950_p1;
reg   [31:0] reg_file_19_load_reg_2572;
reg   [31:0] reg_file_20_load_load_fu_953_p1;
reg   [31:0] reg_file_20_load_reg_2578;
reg   [31:0] reg_file_21_load_load_fu_956_p1;
reg   [31:0] reg_file_21_load_reg_2584;
reg   [31:0] reg_file_22_load_load_fu_959_p1;
reg   [31:0] reg_file_22_load_reg_2590;
reg   [31:0] reg_file_23_load_load_fu_962_p1;
reg   [31:0] reg_file_23_load_reg_2596;
reg   [31:0] reg_file_24_load_load_fu_965_p1;
reg   [31:0] reg_file_24_load_reg_2602;
reg   [31:0] reg_file_25_load_load_fu_968_p1;
reg   [31:0] reg_file_25_load_reg_2608;
reg   [31:0] reg_file_26_load_load_fu_971_p1;
reg   [31:0] reg_file_26_load_reg_2614;
reg   [31:0] reg_file_27_load_load_fu_974_p1;
reg   [31:0] reg_file_27_load_reg_2620;
reg   [31:0] reg_file_28_load_load_fu_977_p1;
reg   [31:0] reg_file_28_load_reg_2626;
reg   [31:0] reg_file_29_load_load_fu_980_p1;
reg   [31:0] reg_file_29_load_reg_2632;
reg   [31:0] reg_file_30_load_load_fu_983_p1;
reg   [31:0] reg_file_30_load_reg_2638;
reg   [31:0] reg_file_31_load_load_fu_986_p1;
reg   [31:0] reg_file_31_load_reg_2644;
reg   [31:0] reg_file_32_load_load_fu_989_p1;
reg   [31:0] reg_file_32_load_reg_2650;
reg   [31:0] instruction_reg_2656;
wire   [4:0] d_i_opcode_fu_992_p4;
reg   [4:0] d_i_opcode_reg_2672;
reg   [4:0] d_i_rd_reg_2678;
reg   [2:0] d_i_func3_reg_2684;
reg   [4:0] d_i_rs1_reg_2695;
reg   [4:0] d_i_rs2_reg_2700;
reg   [0:0] f7_6_reg_2707;
wire   [0:0] d_i_is_load_fu_1051_p2;
wire   [0:0] grp_fu_650_p2;
reg   [0:0] d_i_is_store_reg_2719;
wire   [0:0] d_i_is_jalr_fu_1057_p2;
wire   [0:0] d_i_is_lui_fu_1063_p2;
reg   [0:0] d_i_is_lui_reg_2728;
wire   [0:0] d_i_is_op_imm_fu_1069_p2;
reg   [0:0] d_i_is_op_imm_reg_2733;
wire   [1:0] opch_fu_1075_p4;
wire   [2:0] opcl_fu_1085_p4;
wire   [17:0] trunc_ln261_fu_1273_p1;
reg   [17:0] trunc_ln261_reg_2745;
wire   [31:0] rv2_fu_1277_p34;
reg   [31:0] rv2_reg_2750;
wire   [31:0] zext_ln123_fu_1344_p1;
wire   [31:0] select_ln117_fu_1354_p3;
reg   [31:0] select_ln117_reg_2762;
wire   [0:0] result_1_fu_1496_p2;
reg   [0:0] result_1_reg_2767;
wire   [31:0] result_28_fu_1513_p2;
reg   [31:0] result_28_reg_2772;
wire   [31:0] result_27_fu_1535_p3;
reg   [31:0] result_27_reg_2777;
wire   [31:0] result_24_fu_1542_p2;
reg   [31:0] result_24_reg_2782;
wire   [0:0] result_23_fu_1548_p2;
reg   [0:0] result_23_reg_2787;
wire   [0:0] result_22_fu_1554_p2;
reg   [0:0] result_22_reg_2792;
wire   [31:0] result_21_fu_1564_p2;
reg   [31:0] result_21_reg_2797;
wire   [31:0] result_20_fu_1581_p3;
reg   [31:0] result_20_reg_2802;
wire   [31:0] result_17_fu_1589_p2;
reg   [31:0] result_17_reg_2807;
wire   [31:0] zext_ln101_fu_1595_p1;
wire   [31:0] result_15_fu_1610_p2;
reg   [31:0] result_15_reg_2817;
wire   [31:0] result_14_fu_1632_p3;
reg   [31:0] result_14_reg_2822;
wire   [31:0] result_11_fu_1639_p2;
reg   [31:0] result_11_reg_2827;
wire   [0:0] grp_fu_655_p2;
reg   [0:0] result_10_reg_2832;
wire   [0:0] grp_fu_659_p2;
reg   [0:0] result_9_reg_2837;
wire   [31:0] result_8_fu_1649_p2;
reg   [31:0] result_8_reg_2842;
wire   [31:0] result_7_fu_1672_p3;
reg   [31:0] result_7_reg_2847;
wire   [31:0] result_4_fu_1680_p2;
reg   [31:0] result_4_reg_2852;
wire   [1:0] a01_fu_1706_p1;
reg   [1:0] a01_reg_2857;
wire    ap_CS_fsm_state5;
wire   [1:0] msize_fu_1710_p4;
wire   [3:0] shl_ln245_fu_1746_p2;
wire   [31:0] shl_ln245_2_fu_1765_p2;
wire   [3:0] shl_ln242_fu_1785_p2;
wire   [31:0] shl_ln242_2_fu_1804_p2;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln196_fu_1821_p2;
reg   [0:0] icmp_ln196_reg_2908;
wire   [0:0] icmp_ln196_1_fu_1826_p2;
reg   [0:0] icmp_ln196_1_reg_2913;
wire   [0:0] icmp_ln196_2_fu_1831_p2;
reg   [0:0] icmp_ln196_2_reg_2918;
reg   [2:0] d_i_type_reg_458;
wire   [19:0] d_i_imm_fu_1220_p5;
reg  signed [19:0] ap_phi_mux_d_i_imm_6_phi_fu_549_p12;
reg  signed [19:0] d_i_imm_6_reg_546;
wire  signed [19:0] sext_ln41_fu_1152_p1;
wire  signed [19:0] sext_ln40_fu_1173_p1;
wire  signed [19:0] sext_ln39_fu_1187_p1;
reg   [31:0] ap_phi_mux_result_29_phi_fu_569_p48;
reg   [31:0] result_29_reg_565;
wire   [31:0] zext_ln114_fu_1686_p1;
wire   [31:0] zext_ln69_1_fu_1690_p1;
wire   [31:0] zext_ln67_1_fu_1694_p1;
wire   [31:0] zext_ln69_fu_1698_p1;
wire   [31:0] zext_ln67_fu_1702_p1;
reg   [31:0] ap_phi_mux_reg_file_phi_fu_625_p16;
reg   [31:0] reg_file_reg_622;
wire    ap_CS_fsm_state7;
wire   [31:0] zext_ln204_fu_1910_p1;
wire  signed [31:0] sext_ln207_fu_1923_p1;
wire  signed [31:0] sext_ln203_fu_1905_p1;
wire   [31:0] zext_ln208_fu_1928_p1;
wire   [63:0] zext_ln14_fu_891_p1;
wire   [63:0] zext_ln248_fu_1725_p1;
wire   [63:0] zext_ln245_3_fu_1772_p1;
wire   [63:0] zext_ln242_3_fu_1811_p1;
wire   [63:0] zext_ln183_fu_1816_p1;
reg   [31:0] nbi_fu_262;
wire   [31:0] add_ln46_fu_2196_p2;
wire    ap_CS_fsm_state8;
wire   [0:0] or_ln20_fu_2190_p2;
wire    ap_CS_fsm_state9;
reg   [15:0] pc_fu_266;
wire   [15:0] grp_fu_697_p2;
wire   [15:0] grp_fu_702_p2;
wire   [15:0] next_pc_4_fu_2157_p3;
wire   [15:0] pc_1_fu_717_p1;
wire   [0:0] cond_fu_2109_p1;
reg   [31:0] reg_file_1_fu_270;
wire   [0:0] icmp_ln25_fu_1933_p2;
wire   [0:0] or_ln28_fu_1943_p2;
reg   [31:0] reg_file_2_fu_274;
reg   [31:0] reg_file_3_fu_278;
reg   [31:0] reg_file_4_fu_282;
reg   [31:0] reg_file_5_fu_286;
reg   [31:0] reg_file_6_fu_290;
reg   [31:0] reg_file_7_fu_294;
reg   [31:0] reg_file_8_fu_298;
reg   [31:0] reg_file_9_fu_302;
reg   [31:0] reg_file_10_fu_306;
reg   [31:0] reg_file_11_fu_310;
reg   [31:0] reg_file_12_fu_314;
reg   [31:0] reg_file_13_fu_318;
reg   [31:0] reg_file_14_fu_322;
reg   [31:0] reg_file_15_fu_326;
reg   [31:0] reg_file_16_fu_330;
reg   [31:0] reg_file_17_fu_334;
reg   [31:0] reg_file_18_fu_338;
reg   [31:0] reg_file_19_fu_342;
reg   [31:0] reg_file_20_fu_346;
reg   [31:0] reg_file_21_fu_350;
reg   [31:0] reg_file_22_fu_354;
reg   [31:0] reg_file_23_fu_358;
reg   [31:0] reg_file_24_fu_362;
reg   [31:0] reg_file_25_fu_366;
reg   [31:0] reg_file_26_fu_370;
reg   [31:0] reg_file_27_fu_374;
reg   [31:0] reg_file_28_fu_378;
reg   [31:0] reg_file_29_fu_382;
reg   [31:0] reg_file_30_fu_386;
reg   [31:0] reg_file_31_fu_390;
reg   [31:0] reg_file_32_fu_394;
reg   [4:0] grp_fu_650_p0;
wire   [31:0] rv1_fu_1233_p34;
wire  signed [31:0] sext_ln91_fu_1316_p1;
reg   [31:0] grp_fu_667_p1;
reg   [31:0] grp_fu_678_p1;
wire   [15:0] grp_fu_687_p4;
wire   [0:0] d_imm_inst_31_fu_1101_p3;
wire   [0:0] d_imm_inst_7_fu_1124_p3;
wire   [5:0] tmp_4_fu_1131_p4;
wire   [3:0] d_imm_inst_11_8_fu_1115_p4;
wire   [11:0] d_i_imm_4_fu_1140_p5;
wire   [6:0] tmp_2_fu_1157_p4;
wire   [11:0] d_i_imm_3_fu_1166_p3;
wire   [11:0] d_i_imm_2_fu_1178_p4;
wire   [7:0] tmp_fu_1202_p4;
wire   [0:0] d_imm_inst_20_fu_1108_p3;
wire   [9:0] tmp_1_fu_1211_p4;
wire   [15:0] pc4_fu_1329_p2;
wire   [15:0] npc4_fu_1338_p2;
wire   [31:0] imm12_fu_1321_p3;
wire   [31:0] zext_ln120_fu_1334_p1;
wire   [31:0] result_2_fu_1348_p2;
wire   [0:0] icmp_ln41_fu_1379_p2;
wire   [0:0] icmp_ln35_4_fu_1417_p2;
wire   [0:0] icmp_ln36_fu_1367_p2;
wire   [0:0] icmp_ln37_fu_1373_p2;
wire   [0:0] icmp_ln35_3_fu_1412_p2;
wire   [0:0] icmp_ln35_2_fu_1407_p2;
wire   [0:0] xor_ln41_fu_1385_p2;
wire   [0:0] icmp_ln35_1_fu_1402_p2;
wire   [0:0] icmp_ln35_fu_1397_p2;
wire   [0:0] icmp_ln42_fu_1391_p2;
wire   [0:0] xor_ln43_fu_1361_p2;
wire   [0:0] or_ln35_fu_1430_p2;
wire   [0:0] select_ln35_fu_1422_p3;
wire   [0:0] select_ln35_1_fu_1436_p3;
wire   [0:0] or_ln35_1_fu_1444_p2;
wire   [0:0] or_ln35_2_fu_1466_p2;
wire   [0:0] select_ln35_3_fu_1458_p3;
wire   [0:0] select_ln35_2_fu_1450_p3;
wire   [0:0] icmp_ln35_6_fu_1485_p2;
wire   [0:0] icmp_ln35_5_fu_1480_p2;
wire   [0:0] and_ln35_fu_1490_p2;
wire   [0:0] select_ln35_4_fu_1472_p3;
wire   [0:0] d_i_is_r_type_fu_1095_p2;
wire   [4:0] shift_3_fu_1502_p1;
wire   [4:0] shift_5_fu_1506_p3;
wire   [31:0] zext_ln74_1_fu_1519_p1;
wire   [31:0] result_25_fu_1523_p2;
wire   [31:0] result_26_fu_1529_p2;
wire   [31:0] zext_ln65_1_fu_1560_p1;
wire   [0:0] and_ln60_1_fu_1570_p2;
wire   [31:0] result_18_fu_1575_p2;
wire   [4:0] shift_fu_1599_p1;
wire   [4:0] shift_2_fu_1603_p3;
wire   [31:0] zext_ln74_fu_1616_p1;
wire   [31:0] result_12_fu_1620_p2;
wire   [31:0] result_13_fu_1626_p2;
wire   [31:0] zext_ln65_fu_1645_p1;
wire   [0:0] and_ln60_fu_1655_p2;
wire   [31:0] result_5_fu_1660_p2;
wire   [31:0] result_6_fu_1666_p2;
wire   [15:0] grp_fu_667_p4;
wire   [15:0] rv2_01_fu_1722_p1;
wire   [0:0] grp_fu_678_p3;
wire   [1:0] and_ln_fu_1734_p3;
wire   [3:0] zext_ln245_1_fu_1742_p1;
wire   [4:0] shl_ln245_1_fu_1753_p3;
wire   [31:0] zext_ln245_fu_1730_p1;
wire   [31:0] zext_ln245_2_fu_1761_p1;
wire   [7:0] rv2_0_fu_1719_p1;
wire   [3:0] zext_ln242_1_fu_1781_p1;
wire   [4:0] shl_ln242_1_fu_1792_p3;
wire   [31:0] zext_ln242_fu_1777_p1;
wire   [31:0] zext_ln242_2_fu_1800_p1;
wire   [7:0] b2_fu_1854_p4;
wire   [7:0] b3_fu_1864_p4;
wire   [7:0] b1_fu_1840_p4;
wire   [7:0] b_4_fu_1884_p3;
wire   [7:0] b0_fu_1836_p1;
wire   [7:0] b_5_fu_1891_p3;
wire  signed [7:0] b_fu_1898_p3;
wire   [15:0] h1_fu_1874_p4;
wire   [15:0] h0_fu_1850_p1;
wire  signed [15:0] h_fu_1915_p3;
wire   [0:0] icmp_ln28_fu_1938_p2;
wire   [17:0] trunc_ln145_fu_2138_p1;
wire   [17:0] add_ln145_fu_2142_p2;
wire   [15:0] next_pc_2_fu_2147_p4;
wire   [0:0] icmp_ln20_fu_2179_p2;
wire   [0:0] icmp_ln20_1_fu_2184_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_condition_467;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
end

rv32i_npp_ip_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .start_pc(start_pc),
    .nb_instruction(nbi_fu_262),
    .nb_instruction_ap_vld(nb_instruction_ap_vld),
    .code_ram_address0(code_ram_address0),
    .code_ram_ce0(code_ram_ce0),
    .code_ram_q0(code_ram_q0),
    .data_ram_address0(data_ram_address0),
    .data_ram_ce0(data_ram_ce0),
    .data_ram_we0(data_ram_we0),
    .data_ram_d0(data_ram_d0),
    .data_ram_q0(data_ram_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

rv32i_npp_ip_mux_32_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_32_5_32_1_1_U1(
    .din0(reg_file_1_load_reg_2464),
    .din1(reg_file_2_load_reg_2470),
    .din2(reg_file_3_load_reg_2476),
    .din3(reg_file_4_load_reg_2482),
    .din4(reg_file_5_load_reg_2488),
    .din5(reg_file_6_load_reg_2494),
    .din6(reg_file_7_load_reg_2500),
    .din7(reg_file_8_load_reg_2506),
    .din8(reg_file_9_load_reg_2512),
    .din9(reg_file_10_load_reg_2518),
    .din10(reg_file_11_load_reg_2524),
    .din11(reg_file_12_load_reg_2530),
    .din12(reg_file_13_load_reg_2536),
    .din13(reg_file_14_load_reg_2542),
    .din14(reg_file_15_load_reg_2548),
    .din15(reg_file_16_load_reg_2554),
    .din16(reg_file_17_load_reg_2560),
    .din17(reg_file_18_load_reg_2566),
    .din18(reg_file_19_load_reg_2572),
    .din19(reg_file_20_load_reg_2578),
    .din20(reg_file_21_load_reg_2584),
    .din21(reg_file_22_load_reg_2590),
    .din22(reg_file_23_load_reg_2596),
    .din23(reg_file_24_load_reg_2602),
    .din24(reg_file_25_load_reg_2608),
    .din25(reg_file_26_load_reg_2614),
    .din26(reg_file_27_load_reg_2620),
    .din27(reg_file_28_load_reg_2626),
    .din28(reg_file_29_load_reg_2632),
    .din29(reg_file_30_load_reg_2638),
    .din30(reg_file_31_load_reg_2644),
    .din31(reg_file_32_load_reg_2650),
    .din32(d_i_rs1_reg_2695),
    .dout(rv1_fu_1233_p34)
);

rv32i_npp_ip_mux_32_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
mux_32_5_32_1_1_U2(
    .din0(reg_file_1_load_reg_2464),
    .din1(reg_file_2_load_reg_2470),
    .din2(reg_file_3_load_reg_2476),
    .din3(reg_file_4_load_reg_2482),
    .din4(reg_file_5_load_reg_2488),
    .din5(reg_file_6_load_reg_2494),
    .din6(reg_file_7_load_reg_2500),
    .din7(reg_file_8_load_reg_2506),
    .din8(reg_file_9_load_reg_2512),
    .din9(reg_file_10_load_reg_2518),
    .din10(reg_file_11_load_reg_2524),
    .din11(reg_file_12_load_reg_2530),
    .din12(reg_file_13_load_reg_2536),
    .din13(reg_file_14_load_reg_2542),
    .din14(reg_file_15_load_reg_2548),
    .din15(reg_file_16_load_reg_2554),
    .din16(reg_file_17_load_reg_2560),
    .din17(reg_file_18_load_reg_2566),
    .din18(reg_file_19_load_reg_2572),
    .din19(reg_file_20_load_reg_2578),
    .din20(reg_file_21_load_reg_2584),
    .din21(reg_file_22_load_reg_2590),
    .din22(reg_file_23_load_reg_2596),
    .din23(reg_file_24_load_reg_2602),
    .din24(reg_file_25_load_reg_2608),
    .din25(reg_file_26_load_reg_2614),
    .din26(reg_file_27_load_reg_2620),
    .din27(reg_file_28_load_reg_2626),
    .din28(reg_file_29_load_reg_2632),
    .din29(reg_file_30_load_reg_2638),
    .din30(reg_file_31_load_reg_2644),
    .din31(reg_file_32_load_reg_2650),
    .din32(d_i_rs2_reg_2700),
    .dout(rv2_fu_1277_p34)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((1'b1 == ap_condition_467)) begin
            d_i_imm_6_reg_546 <= 20'd0;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2)) begin
            d_i_imm_6_reg_546 <= sext_ln39_fu_1187_p1;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd3)) begin
            d_i_imm_6_reg_546 <= sext_ln40_fu_1173_p1;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd4)) begin
            d_i_imm_6_reg_546 <= sext_ln41_fu_1152_p1;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd5)) begin
            d_i_imm_6_reg_546 <= {{instruction_reg_2656[31:12]}};
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd6)) begin
            d_i_imm_6_reg_546 <= d_i_imm_fu_1220_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd0) & (opch_fu_1075_p4 == 2'd3))) begin
        d_i_type_reg_458 <= 3'd4;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd3) & (opch_fu_1075_p4 == 2'd3))) begin
        d_i_type_reg_458 <= 3'd6;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd0) & (opch_fu_1075_p4 == 2'd1))) begin
        d_i_type_reg_458 <= 3'd3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd4) & (opch_fu_1075_p4 == 2'd1))) begin
        d_i_type_reg_458 <= 3'd1;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd4) & (opch_fu_1075_p4 == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd0) & (opch_fu_1075_p4 == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd1) & (opch_fu_1075_p4 == 2'd3)))) begin
        d_i_type_reg_458 <= 3'd2;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd5) & (opch_fu_1075_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd5) & (opch_fu_1075_p4 == 2'd0)))) begin
        d_i_type_reg_458 <= 3'd5;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd4) & (opch_fu_1075_p4 == 2'd3)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd1) & (opch_fu_1075_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd1) & (opch_fu_1075_p4 == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd2) & (opch_fu_1075_p4 == 2'd3)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd2) & (opch_fu_1075_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd2) & (opch_fu_1075_p4 == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd3) & (opch_fu_1075_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd3) & (opch_fu_1075_p4 == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd5) & (opch_fu_1075_p4 == 2'd3)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd6) & (opch_fu_1075_p4 == 2'd3)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd6) & (opch_fu_1075_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd6) & (opch_fu_1075_p4 
    == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opch_fu_1075_p4 == 2'd2)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd7) & (opch_fu_1075_p4 == 2'd3)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd7) & (opch_fu_1075_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1085_p4 == 3'd7) & (opch_fu_1075_p4 == 2'd0)))) begin
        d_i_type_reg_458 <= 3'd7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        nbi_fu_262 <= 32'd1;
    end else if (((or_ln20_fu_2190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        nbi_fu_262 <= add_ln46_fu_2196_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pc_fu_266 <= pc_1_fu_717_p1;
    end else if (((d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        pc_fu_266 <= next_pc_4_fu_2157_p3;
    end else if ((((cond_fu_2109_p1 == 1'd0) & (d_i_type_reg_458 == 3'd4) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state7) & ((d_i_type_reg_458 == 3'd7) | (d_i_type_reg_458 == 3'd0))) | ((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state7)) | ((d_i_type_reg_458 == 3'd3) & (1'b1 == ap_CS_fsm_state7)) | ((d_i_type_reg_458 == 3'd5) & (1'b1 == ap_CS_fsm_state7)))) begin
        pc_fu_266 <= grp_fu_702_p2;
    end else if ((((cond_fu_2109_p1 == 1'd1) & (d_i_type_reg_458 == 3'd4) & (1'b1 == ap_CS_fsm_state7)) | ((d_i_type_reg_458 == 3'd6) & (1'b1 == ap_CS_fsm_state7)))) begin
        pc_fu_266 <= grp_fu_697_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_10_fu_306 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd9))) begin
        reg_file_10_fu_306 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_11_fu_310 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd10))) begin
        reg_file_11_fu_310 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_12_fu_314 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd11))) begin
        reg_file_12_fu_314 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_13_fu_318 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd12))) begin
        reg_file_13_fu_318 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_14_fu_322 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd13))) begin
        reg_file_14_fu_322 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_15_fu_326 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd14))) begin
        reg_file_15_fu_326 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_16_fu_330 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd15))) begin
        reg_file_16_fu_330 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_17_fu_334 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd16))) begin
        reg_file_17_fu_334 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_18_fu_338 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd17))) begin
        reg_file_18_fu_338 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_19_fu_342 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd18))) begin
        reg_file_19_fu_342 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_1_fu_270 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd0))) begin
        reg_file_1_fu_270 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_20_fu_346 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd19))) begin
        reg_file_20_fu_346 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_21_fu_350 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd20))) begin
        reg_file_21_fu_350 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_22_fu_354 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd21))) begin
        reg_file_22_fu_354 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_23_fu_358 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd22))) begin
        reg_file_23_fu_358 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_24_fu_362 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd23))) begin
        reg_file_24_fu_362 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_25_fu_366 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd24))) begin
        reg_file_25_fu_366 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_26_fu_370 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd25))) begin
        reg_file_26_fu_370 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_27_fu_374 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd26))) begin
        reg_file_27_fu_374 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_28_fu_378 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd27))) begin
        reg_file_28_fu_378 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_29_fu_382 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd28))) begin
        reg_file_29_fu_382 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_2_fu_274 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd1))) begin
        reg_file_2_fu_274 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_30_fu_386 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd29))) begin
        reg_file_30_fu_386 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_31_fu_390 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd30))) begin
        reg_file_31_fu_390 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_32_fu_394 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd31))) begin
        reg_file_32_fu_394 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_3_fu_278 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd2))) begin
        reg_file_3_fu_278 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_4_fu_282 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd3))) begin
        reg_file_4_fu_282 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_5_fu_286 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd4))) begin
        reg_file_5_fu_286 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_6_fu_290 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd5))) begin
        reg_file_6_fu_290 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_7_fu_294 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd6))) begin
        reg_file_7_fu_294 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_8_fu_298 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd7))) begin
        reg_file_8_fu_298 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_9_fu_302 <= 32'd0;
    end else if (((or_ln28_fu_1943_p2 == 1'd0) & (icmp_ln25_fu_1933_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (d_i_rd_reg_2678 == 5'd8))) begin
        reg_file_9_fu_302 <= ap_phi_mux_reg_file_phi_fu_625_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        reg_file_reg_622 <= result_29_reg_565;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd5))) begin
        reg_file_reg_622 <= zext_ln208_fu_1928_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd0))) begin
        reg_file_reg_622 <= sext_ln203_fu_1905_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd1))) begin
        reg_file_reg_622 <= sext_ln207_fu_1923_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd2))) begin
        reg_file_reg_622 <= data_ram_q0;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd4))) begin
        reg_file_reg_622 <= zext_ln204_fu_1910_p1;
    end else if ((((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd3)) | ((1'b1 == ap_CS_fsm_state7) & (((d_i_is_load_reg_2715 == 1'd1) & (d_i_func3_reg_2684 == 3'd7)) | ((d_i_is_load_reg_2715 == 1'd1) & (d_i_func3_reg_2684 == 3'd6)))))) begin
        reg_file_reg_622 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd0))) begin
        result_29_reg_565 <= result_7_reg_2847;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd1))) begin
        result_29_reg_565 <= result_8_reg_2842;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd2))) begin
        result_29_reg_565 <= zext_ln67_fu_1702_p1;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd3))) begin
        result_29_reg_565 <= zext_ln69_fu_1698_p1;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd4))) begin
        result_29_reg_565 <= result_11_reg_2827;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd5))) begin
        result_29_reg_565 <= result_14_reg_2822;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd6))) begin
        result_29_reg_565 <= result_15_reg_2817;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd0))) begin
        result_29_reg_565 <= result_20_reg_2802;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd1))) begin
        result_29_reg_565 <= result_21_reg_2797;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd2))) begin
        result_29_reg_565 <= zext_ln67_1_fu_1694_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd3))) begin
        result_29_reg_565 <= zext_ln69_1_fu_1690_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd4))) begin
        result_29_reg_565 <= result_24_reg_2782;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd5))) begin
        result_29_reg_565 <= result_27_reg_2777;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd6))) begin
        result_29_reg_565 <= result_28_reg_2772;
    end else if ((((1'b1 == ap_CS_fsm_state4) & ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd7) | (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd0))) | ((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd0)))) begin
        result_29_reg_565 <= 32'd0;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd7))) begin
        result_29_reg_565 <= result_4_reg_2852;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd7))) begin
        result_29_reg_565 <= result_17_reg_2807;
    end else if (((d_i_is_jalr_reg_2723 == 1'd1) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_565 <= zext_ln101_fu_1595_p1;
    end else if ((((d_i_is_load_reg_2715 == 1'd1) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5)) | ((d_i_type_reg_458 == 3'd3) & (1'b1 == ap_CS_fsm_state5)))) begin
        result_29_reg_565 <= reg_711;
    end else if (((d_i_type_reg_458 == 3'd4) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_565 <= zext_ln114_fu_1686_p1;
    end else if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd6) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_565 <= zext_ln123_fu_1344_p1;
    end else if (((d_i_type_reg_458 == 3'd5) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_565 <= select_ln117_reg_2762;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        a01_reg_2857 <= a01_fu_1706_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_func3_reg_2684 <= {{code_ram_q0[14:12]}};
        d_i_is_jalr_reg_2723 <= d_i_is_jalr_fu_1057_p2;
        d_i_is_load_reg_2715 <= d_i_is_load_fu_1051_p2;
        d_i_is_lui_reg_2728 <= d_i_is_lui_fu_1063_p2;
        d_i_is_op_imm_reg_2733 <= d_i_is_op_imm_fu_1069_p2;
        d_i_is_store_reg_2719 <= grp_fu_650_p2;
        d_i_opcode_reg_2672 <= {{code_ram_q0[6:2]}};
        d_i_rd_reg_2678 <= {{code_ram_q0[11:7]}};
        d_i_rs1_reg_2695 <= {{code_ram_q0[19:15]}};
        d_i_rs2_reg_2700 <= {{code_ram_q0[24:20]}};
        f7_6_reg_2707 <= code_ram_q0[32'd30];
        instruction_reg_2656 <= code_ram_q0;
        reg_file_10_load_load_fu_923_p1 <= reg_file_10_fu_306;
        reg_file_10_load_reg_2518 <= reg_file_10_load_load_fu_923_p1;
        reg_file_11_load_load_fu_926_p1 <= reg_file_11_fu_310;
        reg_file_11_load_reg_2524 <= reg_file_11_load_load_fu_926_p1;
        reg_file_12_load_load_fu_929_p1 <= reg_file_12_fu_314;
        reg_file_12_load_reg_2530 <= reg_file_12_load_load_fu_929_p1;
        reg_file_13_load_load_fu_932_p1 <= reg_file_13_fu_318;
        reg_file_13_load_reg_2536 <= reg_file_13_load_load_fu_932_p1;
        reg_file_14_load_load_fu_935_p1 <= reg_file_14_fu_322;
        reg_file_14_load_reg_2542 <= reg_file_14_load_load_fu_935_p1;
        reg_file_15_load_load_fu_938_p1 <= reg_file_15_fu_326;
        reg_file_15_load_reg_2548 <= reg_file_15_load_load_fu_938_p1;
        reg_file_16_load_load_fu_941_p1 <= reg_file_16_fu_330;
        reg_file_16_load_reg_2554 <= reg_file_16_load_load_fu_941_p1;
        reg_file_17_load_load_fu_944_p1 <= reg_file_17_fu_334;
        reg_file_17_load_reg_2560 <= reg_file_17_load_load_fu_944_p1;
        reg_file_18_load_load_fu_947_p1 <= reg_file_18_fu_338;
        reg_file_18_load_reg_2566 <= reg_file_18_load_load_fu_947_p1;
        reg_file_19_load_load_fu_950_p1 <= reg_file_19_fu_342;
        reg_file_19_load_reg_2572 <= reg_file_19_load_load_fu_950_p1;
        reg_file_1_load_load_fu_896_p1 <= reg_file_1_fu_270;
        reg_file_1_load_reg_2464 <= reg_file_1_load_load_fu_896_p1;
        reg_file_20_load_load_fu_953_p1 <= reg_file_20_fu_346;
        reg_file_20_load_reg_2578 <= reg_file_20_load_load_fu_953_p1;
        reg_file_21_load_load_fu_956_p1 <= reg_file_21_fu_350;
        reg_file_21_load_reg_2584 <= reg_file_21_load_load_fu_956_p1;
        reg_file_22_load_load_fu_959_p1 <= reg_file_22_fu_354;
        reg_file_22_load_reg_2590 <= reg_file_22_load_load_fu_959_p1;
        reg_file_23_load_load_fu_962_p1 <= reg_file_23_fu_358;
        reg_file_23_load_reg_2596 <= reg_file_23_load_load_fu_962_p1;
        reg_file_24_load_load_fu_965_p1 <= reg_file_24_fu_362;
        reg_file_24_load_reg_2602 <= reg_file_24_load_load_fu_965_p1;
        reg_file_25_load_load_fu_968_p1 <= reg_file_25_fu_366;
        reg_file_25_load_reg_2608 <= reg_file_25_load_load_fu_968_p1;
        reg_file_26_load_load_fu_971_p1 <= reg_file_26_fu_370;
        reg_file_26_load_reg_2614 <= reg_file_26_load_load_fu_971_p1;
        reg_file_27_load_load_fu_974_p1 <= reg_file_27_fu_374;
        reg_file_27_load_reg_2620 <= reg_file_27_load_load_fu_974_p1;
        reg_file_28_load_load_fu_977_p1 <= reg_file_28_fu_378;
        reg_file_28_load_reg_2626 <= reg_file_28_load_load_fu_977_p1;
        reg_file_29_load_load_fu_980_p1 <= reg_file_29_fu_382;
        reg_file_29_load_reg_2632 <= reg_file_29_load_load_fu_980_p1;
        reg_file_2_load_load_fu_899_p1 <= reg_file_2_fu_274;
        reg_file_2_load_reg_2470 <= reg_file_2_load_load_fu_899_p1;
        reg_file_30_load_load_fu_983_p1 <= reg_file_30_fu_386;
        reg_file_30_load_reg_2638 <= reg_file_30_load_load_fu_983_p1;
        reg_file_31_load_load_fu_986_p1 <= reg_file_31_fu_390;
        reg_file_31_load_reg_2644 <= reg_file_31_load_load_fu_986_p1;
        reg_file_32_load_load_fu_989_p1 <= reg_file_32_fu_394;
        reg_file_32_load_reg_2650 <= reg_file_32_load_load_fu_989_p1;
        reg_file_3_load_load_fu_902_p1 <= reg_file_3_fu_278;
        reg_file_3_load_reg_2476 <= reg_file_3_load_load_fu_902_p1;
        reg_file_4_load_load_fu_905_p1 <= reg_file_4_fu_282;
        reg_file_4_load_reg_2482 <= reg_file_4_load_load_fu_905_p1;
        reg_file_5_load_load_fu_908_p1 <= reg_file_5_fu_286;
        reg_file_5_load_reg_2488 <= reg_file_5_load_load_fu_908_p1;
        reg_file_6_load_load_fu_911_p1 <= reg_file_6_fu_290;
        reg_file_6_load_reg_2494 <= reg_file_6_load_load_fu_911_p1;
        reg_file_7_load_load_fu_914_p1 <= reg_file_7_fu_294;
        reg_file_7_load_reg_2500 <= reg_file_7_load_load_fu_914_p1;
        reg_file_8_load_load_fu_917_p1 <= reg_file_8_fu_298;
        reg_file_8_load_reg_2506 <= reg_file_8_load_load_fu_917_p1;
        reg_file_9_load_load_fu_920_p1 <= reg_file_9_fu_302;
        reg_file_9_load_reg_2512 <= reg_file_9_load_load_fu_920_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        icmp_ln196_1_reg_2913 <= icmp_ln196_1_fu_1826_p2;
        icmp_ln196_2_reg_2918 <= icmp_ln196_2_fu_1831_p2;
        icmp_ln196_reg_2908 <= icmp_ln196_fu_1821_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pc_2_reg_2452 <= pc_fu_266;
    end
end

always @ (posedge ap_clk) begin
    if ((((d_i_is_load_reg_2715 == 1'd1) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd3) & (1'b1 == ap_CS_fsm_state4)))) begin
        reg_711 <= grp_fu_663_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd3))) begin
        result_10_reg_2832 <= grp_fu_655_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd4))) begin
        result_11_reg_2827 <= result_11_fu_1639_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd5))) begin
        result_14_reg_2822 <= result_14_fu_1632_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd6))) begin
        result_15_reg_2817 <= result_15_fu_1610_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd7))) begin
        result_17_reg_2807 <= result_17_fu_1589_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd4) & (1'b1 == ap_CS_fsm_state4))) begin
        result_1_reg_2767 <= result_1_fu_1496_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd0))) begin
        result_20_reg_2802 <= result_20_fu_1581_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd1))) begin
        result_21_reg_2797 <= result_21_fu_1564_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd2))) begin
        result_22_reg_2792 <= result_22_fu_1554_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd3))) begin
        result_23_reg_2787 <= result_23_fu_1548_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd4))) begin
        result_24_reg_2782 <= result_24_fu_1542_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd5))) begin
        result_27_reg_2777 <= result_27_fu_1535_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd6))) begin
        result_28_reg_2772 <= result_28_fu_1513_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd7))) begin
        result_4_reg_2852 <= result_4_fu_1680_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2) & ~(ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd3) & ~(ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd4) & ~(ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd5) & ~(ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd6) & (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd0))) begin
        result_7_reg_2847 <= result_7_fu_1672_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd1))) begin
        result_8_reg_2842 <= result_8_fu_1649_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1) & (1'b1 == ap_CS_fsm_state4) & (d_i_func3_reg_2684 == 3'd2))) begin
        result_9_reg_2837 <= grp_fu_659_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rv2_reg_2750 <= rv2_fu_1277_p34;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd5) & (1'b1 == ap_CS_fsm_state4))) begin
        select_ln117_reg_2762[31 : 2] <= select_ln117_fu_1354_p3[31 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_jalr_reg_2723 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        trunc_ln261_reg_2745 <= trunc_ln261_fu_1273_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((1'b1 == ap_condition_467)) begin
            ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = 20'd0;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd2)) begin
            ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = sext_ln39_fu_1187_p1;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd3)) begin
            ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = sext_ln40_fu_1173_p1;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd4)) begin
            ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = sext_ln41_fu_1152_p1;
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd5)) begin
            ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = {{instruction_reg_2656[31:12]}};
        end else if ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd6)) begin
            ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = d_i_imm_fu_1220_p5;
        end else begin
            ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = 'bx;
        end
    end else begin
        ap_phi_mux_d_i_imm_6_phi_fu_549_p12 = 'bx;
    end
end

always @ (*) begin
    if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd5))) begin
        ap_phi_mux_reg_file_phi_fu_625_p16 = zext_ln208_fu_1928_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd0))) begin
        ap_phi_mux_reg_file_phi_fu_625_p16 = sext_ln203_fu_1905_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd1))) begin
        ap_phi_mux_reg_file_phi_fu_625_p16 = sext_ln207_fu_1923_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd2))) begin
        ap_phi_mux_reg_file_phi_fu_625_p16 = data_ram_q0;
    end else if (((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd4))) begin
        ap_phi_mux_reg_file_phi_fu_625_p16 = zext_ln204_fu_1910_p1;
    end else if ((((d_i_is_load_reg_2715 == 1'd1) & (1'b1 == ap_CS_fsm_state7) & (d_i_func3_reg_2684 == 3'd3)) | ((1'b1 == ap_CS_fsm_state7) & (((d_i_is_load_reg_2715 == 1'd1) & (d_i_func3_reg_2684 == 3'd7)) | ((d_i_is_load_reg_2715 == 1'd1) & (d_i_func3_reg_2684 == 3'd6)))))) begin
        ap_phi_mux_reg_file_phi_fu_625_p16 = 32'd0;
    end else begin
        ap_phi_mux_reg_file_phi_fu_625_p16 = reg_file_reg_622;
    end
end

always @ (*) begin
    if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd0))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_7_reg_2847;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd1))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_8_reg_2842;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd2))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = zext_ln67_fu_1702_p1;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd3))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = zext_ln69_fu_1698_p1;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd4))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_11_reg_2827;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd5))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_14_reg_2822;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd6))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_15_reg_2817;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd0))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_20_reg_2802;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd1))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_21_reg_2797;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd2))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = zext_ln67_1_fu_1694_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd3))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = zext_ln69_1_fu_1690_p1;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd4))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_24_reg_2782;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd5))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_27_reg_2777;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd6))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_28_reg_2772;
    end else if (((d_i_type_reg_458 == 3'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_func3_reg_2684 == 3'd7))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_4_reg_2852;
    end else if (((d_i_is_load_reg_2715 == 1'd0) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_op_imm_reg_2733 == 1'd1) & (d_i_func3_reg_2684 == 3'd7))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_17_reg_2807;
    end else if ((((d_i_is_load_reg_2715 == 1'd1) & (d_i_is_jalr_reg_2723 == 1'd0) & (d_i_type_reg_458 == 3'd2) & (1'b1 == ap_CS_fsm_state5)) | ((d_i_type_reg_458 == 3'd3) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = reg_711;
    end else if (((d_i_type_reg_458 == 3'd4) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = zext_ln114_fu_1686_p1;
    end else if (((d_i_type_reg_458 == 3'd5) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_569_p48 = select_ln117_reg_2762;
    end else begin
        ap_phi_mux_result_29_phi_fu_569_p48 = result_29_reg_565;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        code_ram_ce0 = 1'b1;
    end else begin
        code_ram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_ram_address0 = zext_ln183_fu_1816_p1;
    end else if (((msize_fu_1710_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1))) begin
        data_ram_address0 = zext_ln242_3_fu_1811_p1;
    end else if (((msize_fu_1710_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1))) begin
        data_ram_address0 = zext_ln245_3_fu_1772_p1;
    end else if (((msize_fu_1710_p4 == 2'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1))) begin
        data_ram_address0 = zext_ln248_fu_1725_p1;
    end else begin
        data_ram_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((msize_fu_1710_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1)) | ((msize_fu_1710_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1)) | ((msize_fu_1710_p4 == 2'd2) & (1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1)))) begin
        data_ram_ce0 = 1'b1;
    end else begin
        data_ram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1))) begin
        if ((msize_fu_1710_p4 == 2'd0)) begin
            data_ram_d0 = shl_ln242_2_fu_1804_p2;
        end else if ((msize_fu_1710_p4 == 2'd1)) begin
            data_ram_d0 = shl_ln245_2_fu_1765_p2;
        end else if ((msize_fu_1710_p4 == 2'd2)) begin
            data_ram_d0 = rv2_reg_2750;
        end else begin
            data_ram_d0 = 'bx;
        end
    end else begin
        data_ram_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (d_i_is_store_reg_2719 == 1'd1))) begin
        if ((msize_fu_1710_p4 == 2'd0)) begin
            data_ram_we0 = shl_ln242_fu_1785_p2;
        end else if ((msize_fu_1710_p4 == 2'd1)) begin
            data_ram_we0 = shl_ln245_fu_1746_p2;
        end else if ((msize_fu_1710_p4 == 2'd2)) begin
            data_ram_we0 = 4'd15;
        end else begin
            data_ram_we0 = 4'd0;
        end
    end else begin
        data_ram_we0 = 4'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_650_p0 = d_i_opcode_reg_2672;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_650_p0 = {{code_ram_q0[6:2]}};
    end else begin
        grp_fu_650_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_667_p1 = result_29_reg_565;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_667_p1 = ap_phi_mux_result_29_phi_fu_569_p48;
    end else begin
        grp_fu_667_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_678_p1 = result_29_reg_565;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_678_p1 = ap_phi_mux_result_29_phi_fu_569_p48;
    end else begin
        grp_fu_678_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        nb_instruction_ap_vld = 1'b1;
    end else begin
        nb_instruction_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((or_ln20_fu_2190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a01_fu_1706_p1 = ap_phi_mux_result_29_phi_fu_569_p48[1:0];

assign add_ln145_fu_2142_p2 = (trunc_ln261_reg_2745 + trunc_ln145_fu_2138_p1);

assign add_ln46_fu_2196_p2 = (nbi_fu_262 + 32'd1);

assign and_ln35_fu_1490_p2 = (icmp_ln35_6_fu_1485_p2 & icmp_ln35_5_fu_1480_p2);

assign and_ln60_1_fu_1570_p2 = (f7_6_reg_2707 & d_i_is_r_type_fu_1095_p2);

assign and_ln60_fu_1655_p2 = (f7_6_reg_2707 & d_i_is_r_type_fu_1095_p2);

assign and_ln_fu_1734_p3 = {{grp_fu_678_p3}, {1'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_condition_467 = ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd0) | ((ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd7) | (ap_phi_mux_d_i_type_phi_fu_468_p50 == 3'd1)));
end

assign ap_phi_mux_d_i_type_phi_fu_468_p50 = d_i_type_reg_458;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b0_fu_1836_p1 = data_ram_q0[7:0];

assign b1_fu_1840_p4 = {{data_ram_q0[15:8]}};

assign b2_fu_1854_p4 = {{data_ram_q0[23:16]}};

assign b3_fu_1864_p4 = {{data_ram_q0[31:24]}};

assign b_4_fu_1884_p3 = ((icmp_ln196_reg_2908[0:0] == 1'b1) ? b2_fu_1854_p4 : b3_fu_1864_p4);

assign b_5_fu_1891_p3 = ((icmp_ln196_1_reg_2913[0:0] == 1'b1) ? b1_fu_1840_p4 : b_4_fu_1884_p3);

assign b_fu_1898_p3 = ((icmp_ln196_2_reg_2918[0:0] == 1'b1) ? b0_fu_1836_p1 : b_5_fu_1891_p3);

assign code_ram_address0 = zext_ln14_fu_891_p1;

assign cond_fu_2109_p1 = ap_phi_mux_reg_file_phi_fu_625_p16[0:0];

assign d_i_imm_2_fu_1178_p4 = {{instruction_reg_2656[31:20]}};

assign d_i_imm_3_fu_1166_p3 = {{tmp_2_fu_1157_p4}, {d_i_rd_reg_2678}};

assign d_i_imm_4_fu_1140_p5 = {{{{d_imm_inst_31_fu_1101_p3}, {d_imm_inst_7_fu_1124_p3}}, {tmp_4_fu_1131_p4}}, {d_imm_inst_11_8_fu_1115_p4}};

assign d_i_imm_fu_1220_p5 = {{{{d_imm_inst_31_fu_1101_p3}, {tmp_fu_1202_p4}}, {d_imm_inst_20_fu_1108_p3}}, {tmp_1_fu_1211_p4}};

assign d_i_is_jalr_fu_1057_p2 = ((d_i_opcode_fu_992_p4 == 5'd25) ? 1'b1 : 1'b0);

assign d_i_is_load_fu_1051_p2 = ((d_i_opcode_fu_992_p4 == 5'd0) ? 1'b1 : 1'b0);

assign d_i_is_lui_fu_1063_p2 = ((d_i_opcode_fu_992_p4 == 5'd13) ? 1'b1 : 1'b0);

assign d_i_is_op_imm_fu_1069_p2 = ((d_i_opcode_fu_992_p4 == 5'd4) ? 1'b1 : 1'b0);

assign d_i_is_r_type_fu_1095_p2 = ((d_i_type_reg_458 == 3'd1) ? 1'b1 : 1'b0);

assign d_i_opcode_fu_992_p4 = {{code_ram_q0[6:2]}};

assign d_imm_inst_11_8_fu_1115_p4 = {{instruction_reg_2656[11:8]}};

assign d_imm_inst_20_fu_1108_p3 = instruction_reg_2656[32'd20];

assign d_imm_inst_31_fu_1101_p3 = instruction_reg_2656[32'd31];

assign d_imm_inst_7_fu_1124_p3 = instruction_reg_2656[32'd7];

assign grp_fu_650_p2 = ((grp_fu_650_p0 == 5'd8) ? 1'b1 : 1'b0);

assign grp_fu_655_p2 = ((rv1_fu_1233_p34 < rv2_fu_1277_p34) ? 1'b1 : 1'b0);

assign grp_fu_659_p2 = (($signed(rv1_fu_1233_p34) < $signed(rv2_fu_1277_p34)) ? 1'b1 : 1'b0);

assign grp_fu_663_p2 = ($signed(rv1_fu_1233_p34) + $signed(sext_ln91_fu_1316_p1));

assign grp_fu_667_p4 = {{grp_fu_667_p1[17:2]}};

assign grp_fu_678_p3 = grp_fu_678_p1[32'd1];

assign grp_fu_687_p4 = {{d_i_imm_6_reg_546[16:1]}};

assign grp_fu_697_p2 = (grp_fu_687_p4 + pc_2_reg_2452);

assign grp_fu_702_p2 = (pc_2_reg_2452 + 16'd1);

assign h0_fu_1850_p1 = data_ram_q0[15:0];

assign h1_fu_1874_p4 = {{data_ram_q0[31:16]}};

assign h_fu_1915_p3 = ((grp_fu_678_p3[0:0] == 1'b1) ? h1_fu_1874_p4 : h0_fu_1850_p1);

assign icmp_ln196_1_fu_1826_p2 = ((a01_reg_2857 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln196_2_fu_1831_p2 = ((a01_reg_2857 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln196_fu_1821_p2 = ((a01_reg_2857 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln20_1_fu_2184_p2 = ((pc_fu_266 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_2179_p2 = ((instruction_reg_2656 != 32'd32871) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_1933_p2 = ((d_i_rd_reg_2678 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_1938_p2 = ((d_i_opcode_reg_2672 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln35_1_fu_1402_p2 = ((d_i_func3_reg_2684 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln35_2_fu_1407_p2 = ((d_i_func3_reg_2684 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln35_3_fu_1412_p2 = ((d_i_func3_reg_2684 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln35_4_fu_1417_p2 = ((d_i_func3_reg_2684 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln35_5_fu_1480_p2 = ((d_i_func3_reg_2684 != 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln35_6_fu_1485_p2 = ((d_i_func3_reg_2684 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_1397_p2 = ((d_i_func3_reg_2684 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_1367_p2 = ((rv1_fu_1233_p34 == rv2_fu_1277_p34) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_1373_p2 = ((rv1_fu_1233_p34 != rv2_fu_1277_p34) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_1379_p2 = (($signed(rv1_fu_1233_p34) < $signed(rv2_fu_1277_p34)) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_1391_p2 = ((rv1_fu_1233_p34 < rv2_fu_1277_p34) ? 1'b1 : 1'b0);

assign imm12_fu_1321_p3 = {{ap_phi_mux_d_i_imm_6_phi_fu_549_p12}, {12'd0}};

assign msize_fu_1710_p4 = {{instruction_reg_2656[13:12]}};

assign next_pc_2_fu_2147_p4 = {{add_ln145_fu_2142_p2[17:2]}};

assign next_pc_4_fu_2157_p3 = ((d_i_is_jalr_reg_2723[0:0] == 1'b1) ? next_pc_2_fu_2147_p4 : grp_fu_702_p2);

assign npc4_fu_1338_p2 = (pc4_fu_1329_p2 + 16'd4);

assign opch_fu_1075_p4 = {{code_ram_q0[6:5]}};

assign opcl_fu_1085_p4 = {{code_ram_q0[4:2]}};

assign or_ln20_fu_2190_p2 = (icmp_ln20_fu_2179_p2 | icmp_ln20_1_fu_2184_p2);

assign or_ln28_fu_1943_p2 = (icmp_ln28_fu_1938_p2 | grp_fu_650_p2);

assign or_ln35_1_fu_1444_p2 = (icmp_ln35_2_fu_1407_p2 | icmp_ln35_1_fu_1402_p2);

assign or_ln35_2_fu_1466_p2 = (or_ln35_fu_1430_p2 | or_ln35_1_fu_1444_p2);

assign or_ln35_fu_1430_p2 = (icmp_ln35_4_fu_1417_p2 | icmp_ln35_3_fu_1412_p2);

assign pc4_fu_1329_p2 = pc_2_reg_2452 << 16'd2;

assign pc_1_fu_717_p1 = start_pc[15:0];

assign result_11_fu_1639_p2 = (rv2_fu_1277_p34 ^ rv1_fu_1233_p34);

assign result_12_fu_1620_p2 = $signed(rv1_fu_1233_p34) >>> zext_ln74_fu_1616_p1;

assign result_13_fu_1626_p2 = rv1_fu_1233_p34 >> zext_ln74_fu_1616_p1;

assign result_14_fu_1632_p3 = ((f7_6_reg_2707[0:0] == 1'b1) ? result_12_fu_1620_p2 : result_13_fu_1626_p2);

assign result_15_fu_1610_p2 = (rv2_fu_1277_p34 | rv1_fu_1233_p34);

assign result_17_fu_1589_p2 = (sext_ln91_fu_1316_p1 & rv1_fu_1233_p34);

assign result_18_fu_1575_p2 = ($signed(rv1_fu_1233_p34) - $signed(sext_ln91_fu_1316_p1));

assign result_1_fu_1496_p2 = (select_ln35_4_fu_1472_p3 & and_ln35_fu_1490_p2);

assign result_20_fu_1581_p3 = ((and_ln60_1_fu_1570_p2[0:0] == 1'b1) ? result_18_fu_1575_p2 : grp_fu_663_p2);

assign result_21_fu_1564_p2 = rv1_fu_1233_p34 << zext_ln65_1_fu_1560_p1;

assign result_22_fu_1554_p2 = (($signed(sext_ln91_fu_1316_p1) > $signed(rv1_fu_1233_p34)) ? 1'b1 : 1'b0);

assign result_23_fu_1548_p2 = ((sext_ln91_fu_1316_p1 > rv1_fu_1233_p34) ? 1'b1 : 1'b0);

assign result_24_fu_1542_p2 = (sext_ln91_fu_1316_p1 ^ rv1_fu_1233_p34);

assign result_25_fu_1523_p2 = $signed(rv1_fu_1233_p34) >>> zext_ln74_1_fu_1519_p1;

assign result_26_fu_1529_p2 = rv1_fu_1233_p34 >> zext_ln74_1_fu_1519_p1;

assign result_27_fu_1535_p3 = ((f7_6_reg_2707[0:0] == 1'b1) ? result_25_fu_1523_p2 : result_26_fu_1529_p2);

assign result_28_fu_1513_p2 = (sext_ln91_fu_1316_p1 | rv1_fu_1233_p34);

assign result_2_fu_1348_p2 = (imm12_fu_1321_p3 + zext_ln120_fu_1334_p1);

assign result_4_fu_1680_p2 = (rv2_fu_1277_p34 & rv1_fu_1233_p34);

assign result_5_fu_1660_p2 = (rv1_fu_1233_p34 - rv2_fu_1277_p34);

assign result_6_fu_1666_p2 = (rv2_fu_1277_p34 + rv1_fu_1233_p34);

assign result_7_fu_1672_p3 = ((and_ln60_fu_1655_p2[0:0] == 1'b1) ? result_5_fu_1660_p2 : result_6_fu_1666_p2);

assign result_8_fu_1649_p2 = rv1_fu_1233_p34 << zext_ln65_fu_1645_p1;

assign rv2_01_fu_1722_p1 = rv2_reg_2750[15:0];

assign rv2_0_fu_1719_p1 = rv2_reg_2750[7:0];

assign select_ln117_fu_1354_p3 = ((d_i_is_lui_reg_2728[0:0] == 1'b1) ? imm12_fu_1321_p3 : result_2_fu_1348_p2);

assign select_ln35_1_fu_1436_p3 = ((icmp_ln35_2_fu_1407_p2[0:0] == 1'b1) ? grp_fu_659_p2 : xor_ln41_fu_1385_p2);

assign select_ln35_2_fu_1450_p3 = ((icmp_ln35_fu_1397_p2[0:0] == 1'b1) ? icmp_ln42_fu_1391_p2 : xor_ln43_fu_1361_p2);

assign select_ln35_3_fu_1458_p3 = ((or_ln35_fu_1430_p2[0:0] == 1'b1) ? select_ln35_fu_1422_p3 : select_ln35_1_fu_1436_p3);

assign select_ln35_4_fu_1472_p3 = ((or_ln35_2_fu_1466_p2[0:0] == 1'b1) ? select_ln35_3_fu_1458_p3 : select_ln35_2_fu_1450_p3);

assign select_ln35_fu_1422_p3 = ((icmp_ln35_4_fu_1417_p2[0:0] == 1'b1) ? icmp_ln36_fu_1367_p2 : icmp_ln37_fu_1373_p2);

assign sext_ln203_fu_1905_p1 = b_fu_1898_p3;

assign sext_ln207_fu_1923_p1 = h_fu_1915_p3;

assign sext_ln39_fu_1187_p1 = $signed(d_i_imm_2_fu_1178_p4);

assign sext_ln40_fu_1173_p1 = $signed(d_i_imm_3_fu_1166_p3);

assign sext_ln41_fu_1152_p1 = $signed(d_i_imm_4_fu_1140_p5);

assign sext_ln91_fu_1316_p1 = ap_phi_mux_d_i_imm_6_phi_fu_549_p12;

assign shift_2_fu_1603_p3 = ((d_i_is_r_type_fu_1095_p2[0:0] == 1'b1) ? shift_fu_1599_p1 : d_i_rs2_reg_2700);

assign shift_3_fu_1502_p1 = ap_phi_mux_d_i_imm_6_phi_fu_549_p12[4:0];

assign shift_5_fu_1506_p3 = ((d_i_is_r_type_fu_1095_p2[0:0] == 1'b1) ? shift_3_fu_1502_p1 : d_i_rs2_reg_2700);

assign shift_fu_1599_p1 = rv2_fu_1277_p34[4:0];

assign shl_ln242_1_fu_1792_p3 = {{a01_fu_1706_p1}, {3'd0}};

assign shl_ln242_2_fu_1804_p2 = zext_ln242_fu_1777_p1 << zext_ln242_2_fu_1800_p1;

assign shl_ln242_fu_1785_p2 = 4'd1 << zext_ln242_1_fu_1781_p1;

assign shl_ln245_1_fu_1753_p3 = {{grp_fu_678_p3}, {4'd0}};

assign shl_ln245_2_fu_1765_p2 = zext_ln245_fu_1730_p1 << zext_ln245_2_fu_1761_p1;

assign shl_ln245_fu_1746_p2 = 4'd3 << zext_ln245_1_fu_1742_p1;

assign tmp_1_fu_1211_p4 = {{instruction_reg_2656[30:21]}};

assign tmp_2_fu_1157_p4 = {{instruction_reg_2656[31:25]}};

assign tmp_4_fu_1131_p4 = {{instruction_reg_2656[30:25]}};

assign tmp_fu_1202_p4 = {{instruction_reg_2656[19:12]}};

assign trunc_ln145_fu_2138_p1 = d_i_imm_6_reg_546[17:0];

assign trunc_ln261_fu_1273_p1 = rv1_fu_1233_p34[17:0];

assign xor_ln41_fu_1385_p2 = (icmp_ln41_fu_1379_p2 ^ 1'd1);

assign xor_ln43_fu_1361_p2 = (grp_fu_655_p2 ^ 1'd1);

assign zext_ln101_fu_1595_p1 = npc4_fu_1338_p2;

assign zext_ln114_fu_1686_p1 = result_1_reg_2767;

assign zext_ln120_fu_1334_p1 = pc4_fu_1329_p2;

assign zext_ln123_fu_1344_p1 = npc4_fu_1338_p2;

assign zext_ln14_fu_891_p1 = pc_fu_266;

assign zext_ln183_fu_1816_p1 = grp_fu_667_p4;

assign zext_ln204_fu_1910_p1 = $unsigned(b_fu_1898_p3);

assign zext_ln208_fu_1928_p1 = $unsigned(h_fu_1915_p3);

assign zext_ln242_1_fu_1781_p1 = a01_fu_1706_p1;

assign zext_ln242_2_fu_1800_p1 = shl_ln242_1_fu_1792_p3;

assign zext_ln242_3_fu_1811_p1 = grp_fu_667_p4;

assign zext_ln242_fu_1777_p1 = rv2_0_fu_1719_p1;

assign zext_ln245_1_fu_1742_p1 = and_ln_fu_1734_p3;

assign zext_ln245_2_fu_1761_p1 = shl_ln245_1_fu_1753_p3;

assign zext_ln245_3_fu_1772_p1 = grp_fu_667_p4;

assign zext_ln245_fu_1730_p1 = rv2_01_fu_1722_p1;

assign zext_ln248_fu_1725_p1 = grp_fu_667_p4;

assign zext_ln65_1_fu_1560_p1 = shift_5_fu_1506_p3;

assign zext_ln65_fu_1645_p1 = shift_2_fu_1603_p3;

assign zext_ln67_1_fu_1694_p1 = result_22_reg_2792;

assign zext_ln67_fu_1702_p1 = result_9_reg_2837;

assign zext_ln69_1_fu_1690_p1 = result_23_reg_2787;

assign zext_ln69_fu_1698_p1 = result_10_reg_2832;

assign zext_ln74_1_fu_1519_p1 = shift_5_fu_1506_p3;

assign zext_ln74_fu_1616_p1 = shift_2_fu_1603_p3;

always @ (posedge ap_clk) begin
    select_ln117_reg_2762[1:0] <= 2'b00;
end

endmodule //rv32i_npp_ip
