// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rv32i_npp_ip_rv32i_npp_ip,hls_ip_2023_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.688200,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=256,HLS_SYN_DSP=0,HLS_SYN_FF=2020,HLS_SYN_LUT=3662,HLS_VERSION=2023_2_1}" *)

module rv32i_npp_ip (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 20;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] start_pc;
wire   [15:0] code_ram_address0;
reg    code_ram_ce0;
wire   [31:0] code_ram_q0;
reg   [15:0] data_ram_address0;
reg    data_ram_ce0;
reg   [3:0] data_ram_we0;
reg   [31:0] data_ram_d0;
wire   [31:0] data_ram_q0;
reg    nb_instruction_ap_vld;
wire   [31:0] grp_fu_619_p2;
reg   [31:0] reg_645;
wire    ap_CS_fsm_state4;
reg   [2:0] d_i_type_reg_462;
reg   [0:0] d_i_is_jalr_reg_2667;
reg   [0:0] d_i_is_load_reg_2659;
reg   [15:0] pc_1_reg_2600;
wire    ap_CS_fsm_state2;
reg   [31:0] instruction_reg_2613;
wire    ap_CS_fsm_state3;
wire   [4:0] d_i_opcode_fu_926_p4;
reg   [4:0] d_i_opcode_reg_2626;
reg   [4:0] d_i_rd_reg_2631;
reg   [7:0] d_imm_inst_19_12_reg_2637;
reg   [2:0] d_i_func3_reg_2642;
reg   [4:0] d_i_rs2_reg_2653;
wire   [0:0] d_i_is_load_fu_986_p2;
wire   [0:0] d_i_is_store_fu_992_p2;
reg   [0:0] d_i_is_store_reg_2663;
wire   [0:0] d_i_is_jalr_fu_998_p2;
wire   [0:0] d_i_is_lui_fu_1004_p2;
reg   [0:0] d_i_is_lui_reg_2672;
wire   [0:0] d_i_is_op_imm_fu_1010_p2;
reg   [0:0] d_i_is_op_imm_reg_2677;
wire   [1:0] opch_fu_1016_p4;
wire   [2:0] opcl_fu_1026_p4;
wire   [0:0] d_i_is_r_type_fu_1036_p2;
reg   [0:0] d_i_is_r_type_reg_2689;
reg   [0:0] d_imm_inst_31_reg_2697;
reg   [3:0] d_imm_inst_11_8_reg_2703;
reg   [0:0] d_imm_inst_7_reg_2708;
wire   [31:0] rv1_fu_1068_p67;
reg   [31:0] rv1_reg_2713;
wire   [17:0] trunc_ln254_fu_1204_p1;
reg   [17:0] trunc_ln254_reg_2741;
wire   [31:0] rv2_fu_1208_p67;
reg   [31:0] rv2_reg_2746;
wire   [17:0] trunc_ln74_fu_1444_p1;
reg   [17:0] trunc_ln74_reg_2765;
wire   [31:0] zext_ln106_fu_1471_p1;
wire   [31:0] select_ln100_fu_1481_p3;
reg   [31:0] select_ln100_reg_2775;
wire   [0:0] result_1_fu_1615_p2;
reg   [0:0] result_1_reg_2780;
wire   [31:0] result_28_fu_1631_p2;
wire   [31:0] result_27_fu_1650_p3;
reg   [31:0] result_27_reg_2790;
wire   [31:0] result_24_fu_1658_p2;
wire   [0:0] result_23_fu_1663_p2;
reg   [0:0] result_23_reg_2800;
wire   [0:0] result_22_fu_1668_p2;
reg   [0:0] result_22_reg_2805;
wire   [31:0] result_21_fu_1677_p2;
reg   [31:0] result_21_reg_2810;
wire   [31:0] result_20_fu_1692_p3;
reg   [31:0] result_20_reg_2815;
wire   [31:0] result_17_fu_1700_p2;
wire   [31:0] zext_ln84_fu_1705_p1;
wire   [31:0] result_15_fu_1718_p2;
wire   [31:0] result_14_fu_1736_p3;
reg   [31:0] result_14_reg_2835;
wire   [31:0] result_11_fu_1744_p2;
wire   [31:0] zext_ln52_fu_1748_p1;
wire   [31:0] zext_ln50_fu_1752_p1;
wire   [31:0] result_8_fu_1760_p2;
reg   [31:0] result_8_reg_2855;
wire   [31:0] result_7_fu_1778_p3;
wire   [31:0] result_4_fu_1786_p2;
wire   [1:0] a01_fu_1802_p1;
reg   [1:0] a01_reg_2870;
wire    ap_CS_fsm_state5;
wire   [1:0] msize_fu_1806_p4;
reg   [1:0] msize_reg_2877;
wire   [15:0] grp_fu_630_p4;
reg   [15:0] a1_reg_2881;
wire   [3:0] shl_ln131_fu_1850_p2;
reg   [3:0] shl_ln131_reg_2891;
wire   [31:0] shl_ln131_2_fu_1868_p2;
reg   [31:0] shl_ln131_2_reg_2896;
wire   [3:0] shl_ln128_fu_1882_p2;
wire   [31:0] shl_ln128_2_fu_1901_p2;
wire    ap_CS_fsm_state6;
reg   [31:0] w_reg_2926;
wire  signed [31:0] sext_ln175_fu_2017_p1;
reg  signed [31:0] sext_ln175_reg_2931;
wire   [31:0] zext_ln176_fu_2021_p1;
reg   [31:0] zext_ln176_reg_2936;
wire  signed [31:0] sext_ln179_fu_2033_p1;
reg  signed [31:0] sext_ln179_reg_2941;
wire   [31:0] zext_ln180_fu_2037_p1;
wire   [0:0] icmp_ln12_fu_2321_p2;
reg   [0:0] icmp_ln12_reg_2954;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_phi_mux_d_i_type_phi_fu_465_p26;
wire   [19:0] d_i_imm_fu_1428_p5;
reg  signed [19:0] ap_phi_mux_d_i_imm_5_phi_fu_511_p12;
reg  signed [19:0] d_i_imm_5_reg_507;
wire  signed [19:0] sext_ln143_fu_1362_p1;
wire  signed [19:0] sext_ln142_fu_1383_p1;
wire  signed [19:0] sext_ln141_fu_1397_p1;
reg   [31:0] ap_phi_mux_result_29_phi_fu_531_p48;
reg   [31:0] result_29_reg_527;
wire   [31:0] zext_ln97_fu_1790_p1;
reg    ap_predicate_pred66_state5;
reg    ap_predicate_pred373_state5;
wire   [31:0] zext_ln52_1_fu_1794_p1;
reg    ap_predicate_pred382_state5;
wire   [31:0] zext_ln50_1_fu_1798_p1;
reg    ap_predicate_pred388_state5;
reg    ap_predicate_pred393_state5;
reg    ap_predicate_pred398_state5;
reg    ap_predicate_pred404_state5;
reg    ap_predicate_pred414_state5;
reg   [31:0] ap_phi_mux_result_34_phi_fu_587_p16;
reg   [31:0] result_34_reg_584;
wire   [63:0] zext_ln12_fu_825_p1;
wire   [63:0] zext_ln134_fu_1821_p1;
wire   [63:0] zext_ln128_3_fu_1908_p1;
wire   [63:0] zext_ln155_fu_1913_p1;
wire   [63:0] zext_ln131_3_fu_1918_p1;
reg   [31:0] nbi_fu_266;
wire   [31:0] add_ln36_fu_2340_p2;
wire    ap_CS_fsm_state8;
wire   [0:0] or_ln12_fu_2332_p2;
wire    ap_CS_fsm_state9;
reg   [15:0] pc_fu_270;
wire   [15:0] add_ln239_fu_2237_p2;
wire   [15:0] grp_fu_640_p2;
wire   [15:0] add_ln233_fu_2270_p2;
wire   [15:0] select_ln222_fu_2299_p3;
wire   [15:0] trunc_ln39_fu_651_p1;
reg   [31:0] reg_file_fu_274;
wire   [0:0] and_ln205_fu_2057_p2;
reg   [31:0] reg_file_1_fu_278;
reg   [31:0] reg_file_2_fu_282;
reg   [31:0] reg_file_3_fu_286;
reg   [31:0] reg_file_4_fu_290;
reg   [31:0] reg_file_5_fu_294;
reg   [31:0] reg_file_6_fu_298;
reg   [31:0] reg_file_7_fu_302;
reg   [31:0] reg_file_8_fu_306;
reg   [31:0] reg_file_9_fu_310;
reg   [31:0] reg_file_10_fu_314;
reg   [31:0] reg_file_11_fu_318;
reg   [31:0] reg_file_12_fu_322;
reg   [31:0] reg_file_13_fu_326;
reg   [31:0] reg_file_14_fu_330;
reg   [31:0] reg_file_15_fu_334;
reg   [31:0] reg_file_16_fu_338;
reg   [31:0] reg_file_17_fu_342;
reg   [31:0] reg_file_18_fu_346;
reg   [31:0] reg_file_19_fu_350;
reg   [31:0] reg_file_20_fu_354;
reg   [31:0] reg_file_21_fu_358;
reg   [31:0] reg_file_22_fu_362;
reg   [31:0] reg_file_23_fu_366;
reg   [31:0] reg_file_24_fu_370;
reg   [31:0] reg_file_25_fu_374;
reg   [31:0] reg_file_26_fu_378;
reg   [31:0] reg_file_27_fu_382;
reg   [31:0] reg_file_28_fu_386;
reg   [31:0] reg_file_29_fu_390;
reg   [31:0] reg_file_30_fu_394;
reg   [31:0] reg_file_31_fu_398;
wire  signed [31:0] sext_ln74_fu_1439_p1;
wire   [31:0] rv1_fu_1068_p65;
wire   [4:0] rv1_fu_1068_p66;
wire   [31:0] rv2_fu_1208_p65;
wire   [4:0] rv2_fu_1208_p66;
wire   [5:0] tmp_4_fu_1344_p4;
wire   [11:0] d_i_imm_4_fu_1353_p5;
wire   [6:0] tmp_2_fu_1367_p4;
wire   [11:0] d_i_imm_3_fu_1376_p3;
wire   [11:0] d_i_imm_2_fu_1388_p4;
wire   [0:0] tmp_fu_1412_p3;
wire   [9:0] tmp_1_fu_1419_p4;
wire   [15:0] pc4_fu_1456_p2;
wire   [15:0] npc4_fu_1465_p2;
wire   [31:0] imm12_fu_1448_p3;
wire   [31:0] zext_ln103_fu_1461_p1;
wire   [31:0] result_2_fu_1475_p2;
wire   [0:0] grp_fu_611_p2;
wire   [0:0] icmp_ln24_fu_1502_p2;
wire   [0:0] icmp_ln18_4_fu_1536_p2;
wire   [0:0] icmp_ln19_fu_1494_p2;
wire   [0:0] icmp_ln20_fu_1498_p2;
wire   [0:0] icmp_ln18_3_fu_1531_p2;
wire   [0:0] icmp_ln18_2_fu_1526_p2;
wire   [0:0] grp_fu_615_p2;
wire   [0:0] xor_ln24_fu_1506_p2;
wire   [0:0] icmp_ln18_1_fu_1521_p2;
wire   [0:0] icmp_ln18_fu_1516_p2;
wire   [0:0] icmp_ln25_fu_1512_p2;
wire   [0:0] xor_ln26_fu_1488_p2;
wire   [0:0] or_ln18_fu_1549_p2;
wire   [0:0] select_ln18_fu_1541_p3;
wire   [0:0] select_ln18_1_fu_1555_p3;
wire   [0:0] or_ln18_1_fu_1563_p2;
wire   [0:0] or_ln18_2_fu_1585_p2;
wire   [0:0] select_ln18_3_fu_1577_p3;
wire   [0:0] select_ln18_2_fu_1569_p3;
wire   [0:0] icmp_ln18_6_fu_1604_p2;
wire   [0:0] icmp_ln18_5_fu_1599_p2;
wire   [0:0] and_ln18_fu_1609_p2;
wire   [0:0] select_ln18_4_fu_1591_p3;
wire   [4:0] shift_2_fu_1621_p1;
wire   [4:0] shift_3_fu_1625_p3;
wire   [31:0] zext_ln57_1_fu_1636_p1;
wire   [0:0] grp_fu_623_p3;
wire   [31:0] result_25_fu_1640_p2;
wire   [31:0] result_26_fu_1645_p2;
wire   [31:0] zext_ln48_1_fu_1673_p1;
wire   [0:0] and_ln43_1_fu_1682_p2;
wire   [31:0] result_18_fu_1687_p2;
wire   [4:0] shift_fu_1709_p1;
wire   [4:0] shift_1_fu_1712_p3;
wire   [31:0] zext_ln57_fu_1722_p1;
wire   [31:0] result_12_fu_1726_p2;
wire   [31:0] result_13_fu_1731_p2;
wire   [31:0] zext_ln48_fu_1756_p1;
wire   [0:0] and_ln43_fu_1765_p2;
wire   [31:0] result_5_fu_1770_p2;
wire   [31:0] result_6_fu_1774_p2;
wire   [15:0] rv2_01_fu_1818_p1;
wire   [0:0] tmp_6_fu_1830_p3;
wire   [1:0] and_ln_fu_1838_p3;
wire   [3:0] zext_ln131_1_fu_1846_p1;
wire   [4:0] shl_ln131_1_fu_1856_p3;
wire   [31:0] zext_ln131_fu_1826_p1;
wire   [31:0] zext_ln131_2_fu_1864_p1;
wire   [7:0] rv2_0_fu_1815_p1;
wire   [3:0] zext_ln128_1_fu_1878_p1;
wire   [4:0] shl_ln128_1_fu_1889_p3;
wire   [31:0] zext_ln128_fu_1874_p1;
wire   [31:0] zext_ln128_2_fu_1897_p1;
wire   [0:0] icmp_ln168_fu_1978_p2;
wire   [7:0] b2_fu_1948_p4;
wire   [7:0] b3_fu_1958_p4;
wire   [0:0] icmp_ln168_1_fu_1991_p2;
wire   [7:0] b1_fu_1934_p4;
wire   [7:0] b_4_fu_1983_p3;
wire   [0:0] icmp_ln168_2_fu_2004_p2;
wire   [7:0] b0_fu_1930_p1;
wire   [7:0] b_5_fu_1996_p3;
wire  signed [7:0] b_fu_2009_p3;
wire   [0:0] a1_1_fu_1922_p3;
wire   [15:0] h1_fu_1968_p4;
wire   [15:0] h0_fu_1944_p1;
wire  signed [15:0] h_fu_2025_p3;
wire   [4:0] or_ln205_fu_2046_p2;
wire   [0:0] icmp_ln205_fu_2041_p2;
wire   [0:0] icmp_ln205_1_fu_2051_p2;
wire   [15:0] trunc_ln6_fu_2227_p4;
wire   [0:0] cond_fu_2223_p1;
wire   [15:0] trunc_ln5_fu_2252_p4;
wire   [15:0] select_ln264_fu_2262_p3;
wire   [17:0] add_ln224_fu_2285_p2;
wire   [15:0] trunc_ln4_fu_2289_p4;
wire   [0:0] icmp_ln12_1_fu_2326_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire   [4:0] rv1_fu_1068_p1;
wire   [4:0] rv1_fu_1068_p3;
wire   [4:0] rv1_fu_1068_p5;
wire   [4:0] rv1_fu_1068_p7;
wire   [4:0] rv1_fu_1068_p9;
wire   [4:0] rv1_fu_1068_p11;
wire   [4:0] rv1_fu_1068_p13;
wire   [4:0] rv1_fu_1068_p15;
wire   [4:0] rv1_fu_1068_p17;
wire   [4:0] rv1_fu_1068_p19;
wire   [4:0] rv1_fu_1068_p21;
wire   [4:0] rv1_fu_1068_p23;
wire   [4:0] rv1_fu_1068_p25;
wire   [4:0] rv1_fu_1068_p27;
wire   [4:0] rv1_fu_1068_p29;
wire   [4:0] rv1_fu_1068_p31;
wire  signed [4:0] rv1_fu_1068_p33;
wire  signed [4:0] rv1_fu_1068_p35;
wire  signed [4:0] rv1_fu_1068_p37;
wire  signed [4:0] rv1_fu_1068_p39;
wire  signed [4:0] rv1_fu_1068_p41;
wire  signed [4:0] rv1_fu_1068_p43;
wire  signed [4:0] rv1_fu_1068_p45;
wire  signed [4:0] rv1_fu_1068_p47;
wire  signed [4:0] rv1_fu_1068_p49;
wire  signed [4:0] rv1_fu_1068_p51;
wire  signed [4:0] rv1_fu_1068_p53;
wire  signed [4:0] rv1_fu_1068_p55;
wire  signed [4:0] rv1_fu_1068_p57;
wire  signed [4:0] rv1_fu_1068_p59;
wire  signed [4:0] rv1_fu_1068_p61;
wire  signed [4:0] rv1_fu_1068_p63;
wire   [4:0] rv2_fu_1208_p1;
wire   [4:0] rv2_fu_1208_p3;
wire   [4:0] rv2_fu_1208_p5;
wire   [4:0] rv2_fu_1208_p7;
wire   [4:0] rv2_fu_1208_p9;
wire   [4:0] rv2_fu_1208_p11;
wire   [4:0] rv2_fu_1208_p13;
wire   [4:0] rv2_fu_1208_p15;
wire   [4:0] rv2_fu_1208_p17;
wire   [4:0] rv2_fu_1208_p19;
wire   [4:0] rv2_fu_1208_p21;
wire   [4:0] rv2_fu_1208_p23;
wire   [4:0] rv2_fu_1208_p25;
wire   [4:0] rv2_fu_1208_p27;
wire   [4:0] rv2_fu_1208_p29;
wire   [4:0] rv2_fu_1208_p31;
wire  signed [4:0] rv2_fu_1208_p33;
wire  signed [4:0] rv2_fu_1208_p35;
wire  signed [4:0] rv2_fu_1208_p37;
wire  signed [4:0] rv2_fu_1208_p39;
wire  signed [4:0] rv2_fu_1208_p41;
wire  signed [4:0] rv2_fu_1208_p43;
wire  signed [4:0] rv2_fu_1208_p45;
wire  signed [4:0] rv2_fu_1208_p47;
wire  signed [4:0] rv2_fu_1208_p49;
wire  signed [4:0] rv2_fu_1208_p51;
wire  signed [4:0] rv2_fu_1208_p53;
wire  signed [4:0] rv2_fu_1208_p55;
wire  signed [4:0] rv2_fu_1208_p57;
wire  signed [4:0] rv2_fu_1208_p59;
wire  signed [4:0] rv2_fu_1208_p61;
wire  signed [4:0] rv2_fu_1208_p63;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 nbi_fu_266 = 32'd0;
#0 pc_fu_270 = 16'd0;
#0 reg_file_fu_274 = 32'd0;
#0 reg_file_1_fu_278 = 32'd0;
#0 reg_file_2_fu_282 = 32'd0;
#0 reg_file_3_fu_286 = 32'd0;
#0 reg_file_4_fu_290 = 32'd0;
#0 reg_file_5_fu_294 = 32'd0;
#0 reg_file_6_fu_298 = 32'd0;
#0 reg_file_7_fu_302 = 32'd0;
#0 reg_file_8_fu_306 = 32'd0;
#0 reg_file_9_fu_310 = 32'd0;
#0 reg_file_10_fu_314 = 32'd0;
#0 reg_file_11_fu_318 = 32'd0;
#0 reg_file_12_fu_322 = 32'd0;
#0 reg_file_13_fu_326 = 32'd0;
#0 reg_file_14_fu_330 = 32'd0;
#0 reg_file_15_fu_334 = 32'd0;
#0 reg_file_16_fu_338 = 32'd0;
#0 reg_file_17_fu_342 = 32'd0;
#0 reg_file_18_fu_346 = 32'd0;
#0 reg_file_19_fu_350 = 32'd0;
#0 reg_file_20_fu_354 = 32'd0;
#0 reg_file_21_fu_358 = 32'd0;
#0 reg_file_22_fu_362 = 32'd0;
#0 reg_file_23_fu_366 = 32'd0;
#0 reg_file_24_fu_370 = 32'd0;
#0 reg_file_25_fu_374 = 32'd0;
#0 reg_file_26_fu_378 = 32'd0;
#0 reg_file_27_fu_382 = 32'd0;
#0 reg_file_28_fu_386 = 32'd0;
#0 reg_file_29_fu_390 = 32'd0;
#0 reg_file_30_fu_394 = 32'd0;
#0 reg_file_31_fu_398 = 32'd0;
end

rv32i_npp_ip_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .start_pc(start_pc),
    .nb_instruction(nbi_fu_266),
    .nb_instruction_ap_vld(nb_instruction_ap_vld),
    .code_ram_address0(code_ram_address0),
    .code_ram_ce0(code_ram_ce0),
    .code_ram_q0(code_ram_q0),
    .data_ram_address0(data_ram_address0),
    .data_ram_ce0(data_ram_ce0),
    .data_ram_we0(data_ram_we0),
    .data_ram_d0(data_ram_d0),
    .data_ram_q0(data_ram_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

rv32i_npp_ip_sparsemux_65_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_65_5_32_1_1_U1(
    .din0(reg_file_fu_274),
    .din1(reg_file_1_fu_278),
    .din2(reg_file_2_fu_282),
    .din3(reg_file_3_fu_286),
    .din4(reg_file_4_fu_290),
    .din5(reg_file_5_fu_294),
    .din6(reg_file_6_fu_298),
    .din7(reg_file_7_fu_302),
    .din8(reg_file_8_fu_306),
    .din9(reg_file_9_fu_310),
    .din10(reg_file_10_fu_314),
    .din11(reg_file_11_fu_318),
    .din12(reg_file_12_fu_322),
    .din13(reg_file_13_fu_326),
    .din14(reg_file_14_fu_330),
    .din15(reg_file_15_fu_334),
    .din16(reg_file_16_fu_338),
    .din17(reg_file_17_fu_342),
    .din18(reg_file_18_fu_346),
    .din19(reg_file_19_fu_350),
    .din20(reg_file_20_fu_354),
    .din21(reg_file_21_fu_358),
    .din22(reg_file_22_fu_362),
    .din23(reg_file_23_fu_366),
    .din24(reg_file_24_fu_370),
    .din25(reg_file_25_fu_374),
    .din26(reg_file_26_fu_378),
    .din27(reg_file_27_fu_382),
    .din28(reg_file_28_fu_386),
    .din29(reg_file_29_fu_390),
    .din30(reg_file_30_fu_394),
    .din31(reg_file_31_fu_398),
    .def(rv1_fu_1068_p65),
    .sel(rv1_fu_1068_p66),
    .dout(rv1_fu_1068_p67)
);

rv32i_npp_ip_sparsemux_65_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_65_5_32_1_1_U2(
    .din0(reg_file_fu_274),
    .din1(reg_file_1_fu_278),
    .din2(reg_file_2_fu_282),
    .din3(reg_file_3_fu_286),
    .din4(reg_file_4_fu_290),
    .din5(reg_file_5_fu_294),
    .din6(reg_file_6_fu_298),
    .din7(reg_file_7_fu_302),
    .din8(reg_file_8_fu_306),
    .din9(reg_file_9_fu_310),
    .din10(reg_file_10_fu_314),
    .din11(reg_file_11_fu_318),
    .din12(reg_file_12_fu_322),
    .din13(reg_file_13_fu_326),
    .din14(reg_file_14_fu_330),
    .din15(reg_file_15_fu_334),
    .din16(reg_file_16_fu_338),
    .din17(reg_file_17_fu_342),
    .din18(reg_file_18_fu_346),
    .din19(reg_file_19_fu_350),
    .din20(reg_file_20_fu_354),
    .din21(reg_file_21_fu_358),
    .din22(reg_file_22_fu_362),
    .din23(reg_file_23_fu_366),
    .din24(reg_file_24_fu_370),
    .din25(reg_file_25_fu_374),
    .din26(reg_file_26_fu_378),
    .din27(reg_file_27_fu_382),
    .din28(reg_file_28_fu_386),
    .din29(reg_file_29_fu_390),
    .din30(reg_file_30_fu_394),
    .din31(reg_file_31_fu_398),
    .def(rv2_fu_1208_p65),
    .sel(rv2_fu_1208_p66),
    .dout(rv2_fu_1208_p67)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_d_i_type_phi_fu_465_p26 == 3'd4) & ~(ap_phi_mux_d_i_type_phi_fu_465_p26 == 3'd3) & ~(ap_phi_mux_d_i_type_phi_fu_465_p26 == 3'd2) & ~(ap_phi_mux_d_i_type_phi_fu_465_p26 == 3'd5) & ~(ap_phi_mux_d_i_type_phi_fu_465_p26 == 3'd6) & (1'b1 == ap_CS_fsm_state3))) begin
        d_i_imm_5_reg_507 <= 20'd0;
    end else if (((d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        d_i_imm_5_reg_507 <= sext_ln141_fu_1397_p1;
    end else if (((d_i_type_reg_462 == 3'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        d_i_imm_5_reg_507 <= sext_ln142_fu_1383_p1;
    end else if (((d_i_type_reg_462 == 3'd4) & (1'b1 == ap_CS_fsm_state4))) begin
        d_i_imm_5_reg_507 <= sext_ln143_fu_1362_p1;
    end else if (((d_i_type_reg_462 == 3'd5) & (1'b1 == ap_CS_fsm_state4))) begin
        d_i_imm_5_reg_507 <= {{instruction_reg_2613[31:12]}};
    end else if (((d_i_type_reg_462 == 3'd6) & (1'b1 == ap_CS_fsm_state4))) begin
        d_i_imm_5_reg_507 <= d_i_imm_fu_1428_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd0) & (opch_fu_1016_p4 == 2'd1))) begin
        d_i_type_reg_462 <= 3'd3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd4) & (opch_fu_1016_p4 == 2'd1))) begin
        d_i_type_reg_462 <= 3'd1;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd5) & (opch_fu_1016_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd5) & (opch_fu_1016_p4 == 2'd0)))) begin
        d_i_type_reg_462 <= 3'd5;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd0) & (opch_fu_1016_p4 == 2'd3))) begin
        d_i_type_reg_462 <= 3'd4;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd1) & (opch_fu_1016_p4 == 2'd3)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd4) & (opch_fu_1016_p4 == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd0) & (opch_fu_1016_p4 == 2'd0)))) begin
        d_i_type_reg_462 <= 3'd2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd3) & (opch_fu_1016_p4 == 2'd3))) begin
        d_i_type_reg_462 <= 3'd6;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd2)) | (~(opcl_fu_1026_p4 == 3'd3) & ~(opcl_fu_1026_p4 == 3'd1) & ~(opcl_fu_1026_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd3)) | (~(opcl_fu_1026_p4 == 3'd4) & ~(opcl_fu_1026_p4 == 3'd5) & ~(opcl_fu_1026_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd1)) | (~(opcl_fu_1026_p4 == 3'd4) & ~(opcl_fu_1026_p4 == 3'd5) & ~(opcl_fu_1026_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd0)))) begin
        d_i_type_reg_462 <= 3'd7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        nbi_fu_266 <= 32'd1;
    end else if (((or_ln12_fu_2332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        nbi_fu_266 <= add_ln36_fu_2340_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pc_fu_270 <= trunc_ln39_fu_651_p1;
    end else if (((d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        pc_fu_270 <= select_ln222_fu_2299_p3;
    end else if (((d_i_type_reg_462 == 3'd4) & (1'b1 == ap_CS_fsm_state7))) begin
        pc_fu_270 <= add_ln233_fu_2270_p2;
    end else if ((((d_i_type_reg_462 == 3'd3) & (1'b1 == ap_CS_fsm_state7)) | ((d_i_type_reg_462 == 3'd1) & (1'b1 == ap_CS_fsm_state7)) | ((d_i_type_reg_462 == 3'd5) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state7) & ((d_i_type_reg_462 == 3'd0) | (d_i_type_reg_462 == 3'd7))))) begin
        pc_fu_270 <= grp_fu_640_p2;
    end else if (((d_i_type_reg_462 == 3'd6) & (1'b1 == ap_CS_fsm_state7))) begin
        pc_fu_270 <= add_ln239_fu_2237_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_10_fu_314 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd10) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_10_fu_314 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_11_fu_318 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd11) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_11_fu_318 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_12_fu_322 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd12) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_12_fu_322 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_13_fu_326 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd13) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_13_fu_326 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_14_fu_330 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd14) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_14_fu_330 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_15_fu_334 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd15) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_15_fu_334 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_16_fu_338 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd16) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_16_fu_338 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_17_fu_342 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd17) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_17_fu_342 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_18_fu_346 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd18) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_18_fu_346 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_19_fu_350 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd19) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_19_fu_350 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_1_fu_278 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd1) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_1_fu_278 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_20_fu_354 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd20) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_20_fu_354 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_21_fu_358 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd21) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_21_fu_358 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_22_fu_362 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd22) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_22_fu_362 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_23_fu_366 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd23) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_23_fu_366 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_24_fu_370 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd24) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_24_fu_370 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_25_fu_374 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd25) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_25_fu_374 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_26_fu_378 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd26) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_26_fu_378 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_27_fu_382 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd27) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_27_fu_382 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_28_fu_386 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd28) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_28_fu_386 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_29_fu_390 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd29) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_29_fu_390 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_2_fu_282 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd2) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_2_fu_282 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_30_fu_394 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd30) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_30_fu_394 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_31_fu_398 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd31) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_31_fu_398 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_3_fu_286 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd3) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_3_fu_286 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_4_fu_290 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd4) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_4_fu_290 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_5_fu_294 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd5) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_5_fu_294 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_6_fu_298 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd6) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_6_fu_298 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_7_fu_302 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd7) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_7_fu_302 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_8_fu_306 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd8) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_8_fu_306 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_9_fu_310 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd9) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_9_fu_310 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg_file_fu_274 <= 32'd0;
    end else if (((d_i_rd_reg_2631 == 5'd0) & (1'd1 == and_ln205_fu_2057_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_file_fu_274 <= ap_phi_mux_result_34_phi_fu_587_p16;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_func3_reg_2642 == 3'd0) & (d_i_type_reg_462 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= result_7_fu_1778_p3;
    end else if (((ap_predicate_pred414_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= result_8_reg_2855;
    end else if (((d_i_func3_reg_2642 == 3'd2) & (d_i_type_reg_462 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= zext_ln50_fu_1752_p1;
    end else if (((d_i_func3_reg_2642 == 3'd3) & (d_i_type_reg_462 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= zext_ln52_fu_1748_p1;
    end else if (((d_i_func3_reg_2642 == 3'd4) & (d_i_type_reg_462 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= result_11_fu_1744_p2;
    end else if (((ap_predicate_pred404_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= result_14_reg_2835;
    end else if (((d_i_func3_reg_2642 == 3'd6) & (d_i_type_reg_462 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= result_15_fu_1718_p2;
    end else if (((ap_predicate_pred398_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= result_20_reg_2815;
    end else if (((ap_predicate_pred393_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= result_21_reg_2810;
    end else if (((ap_predicate_pred388_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= zext_ln50_1_fu_1798_p1;
    end else if (((ap_predicate_pred382_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= zext_ln52_1_fu_1794_p1;
    end else if (((d_i_func3_reg_2642 == 3'd4) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2677 == 1'd1))) begin
        result_29_reg_527 <= result_24_fu_1658_p2;
    end else if (((ap_predicate_pred373_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= result_27_reg_2790;
    end else if (((d_i_func3_reg_2642 == 3'd6) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2677 == 1'd1))) begin
        result_29_reg_527 <= result_28_fu_1631_p2;
    end else if ((((1'b1 == ap_CS_fsm_state4) & ((d_i_type_reg_462 == 3'd0) | (d_i_type_reg_462 == 3'd7))) | ((d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2677 == 1'd0)))) begin
        result_29_reg_527 <= 32'd0;
    end else if (((d_i_type_reg_462 == 3'd5) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= select_ln100_reg_2775;
    end else if (((d_i_func3_reg_2642 == 3'd7) & (d_i_type_reg_462 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= result_4_fu_1786_p2;
    end else if (((d_i_func3_reg_2642 == 3'd7) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state4) & (d_i_is_op_imm_reg_2677 == 1'd1))) begin
        result_29_reg_527 <= result_17_fu_1700_p2;
    end else if (((d_i_is_jalr_reg_2667 == 1'd1) & (d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= zext_ln84_fu_1705_p1;
    end else if ((((d_i_type_reg_462 == 3'd3) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred66_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        result_29_reg_527 <= reg_645;
    end else if (((d_i_type_reg_462 == 3'd4) & (1'b1 == ap_CS_fsm_state5))) begin
        result_29_reg_527 <= zext_ln97_fu_1790_p1;
    end else if (((d_i_type_reg_462 == 3'd6) & (1'b1 == ap_CS_fsm_state4))) begin
        result_29_reg_527 <= zext_ln106_fu_1471_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((d_i_is_load_reg_2659 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        result_34_reg_584 <= result_29_reg_527;
    end else if (((d_i_func3_reg_2642 == 3'd5) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        result_34_reg_584 <= zext_ln180_fu_2037_p1;
    end else if (((d_i_func3_reg_2642 == 3'd0) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        result_34_reg_584 <= sext_ln175_reg_2931;
    end else if (((d_i_func3_reg_2642 == 3'd1) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        result_34_reg_584 <= sext_ln179_reg_2941;
    end else if (((d_i_func3_reg_2642 == 3'd2) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        result_34_reg_584 <= w_reg_2926;
    end else if (((d_i_func3_reg_2642 == 3'd4) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        result_34_reg_584 <= zext_ln176_reg_2936;
    end else if ((((d_i_func3_reg_2642 == 3'd3) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state7) & (((d_i_func3_reg_2642 == 3'd6) & (d_i_is_load_reg_2659 == 1'd1)) | ((d_i_func3_reg_2642 == 3'd7) & (d_i_is_load_reg_2659 == 1'd1)))))) begin
        result_34_reg_584 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        a01_reg_2870 <= a01_fu_1802_p1;
        a1_reg_2881 <= {{ap_phi_mux_result_29_phi_fu_531_p48[17:2]}};
        msize_reg_2877 <= {{instruction_reg_2613[13:12]}};
        shl_ln131_2_reg_2896 <= shl_ln131_2_fu_1868_p2;
        shl_ln131_reg_2891 <= shl_ln131_fu_1850_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_predicate_pred373_state5 <= ((d_i_func3_reg_2642 == 3'd5) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (d_i_is_op_imm_reg_2677 == 1'd1));
        ap_predicate_pred382_state5 <= ((d_i_func3_reg_2642 == 3'd3) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (d_i_is_op_imm_reg_2677 == 1'd1));
        ap_predicate_pred388_state5 <= ((d_i_func3_reg_2642 == 3'd2) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (d_i_is_op_imm_reg_2677 == 1'd1));
        ap_predicate_pred393_state5 <= ((d_i_func3_reg_2642 == 3'd1) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (d_i_is_op_imm_reg_2677 == 1'd1));
        ap_predicate_pred398_state5 <= ((d_i_func3_reg_2642 == 3'd0) & (d_i_is_load_reg_2659 == 1'd0) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (d_i_is_op_imm_reg_2677 == 1'd1));
        ap_predicate_pred404_state5 <= ((d_i_func3_reg_2642 == 3'd5) & (d_i_type_reg_462 == 3'd1));
        ap_predicate_pred414_state5 <= ((d_i_func3_reg_2642 == 3'd1) & (d_i_type_reg_462 == 3'd1));
        ap_predicate_pred66_state5 <= ((d_i_is_load_reg_2659 == 1'd1) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2));
        result_14_reg_2835 <= result_14_fu_1736_p3;
        result_1_reg_2780 <= result_1_fu_1615_p2;
        result_20_reg_2815 <= result_20_fu_1692_p3;
        result_21_reg_2810 <= result_21_fu_1677_p2;
        result_22_reg_2805 <= result_22_fu_1668_p2;
        result_23_reg_2800 <= result_23_fu_1663_p2;
        result_27_reg_2790 <= result_27_fu_1650_p3;
        result_8_reg_2855 <= result_8_fu_1760_p2;
        select_ln100_reg_2775[31 : 2] <= select_ln100_fu_1481_p3[31 : 2];
        trunc_ln74_reg_2765 <= trunc_ln74_fu_1444_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_func3_reg_2642 <= {{code_ram_q0[14:12]}};
        d_i_is_jalr_reg_2667 <= d_i_is_jalr_fu_998_p2;
        d_i_is_load_reg_2659 <= d_i_is_load_fu_986_p2;
        d_i_is_lui_reg_2672 <= d_i_is_lui_fu_1004_p2;
        d_i_is_op_imm_reg_2677 <= d_i_is_op_imm_fu_1010_p2;
        d_i_is_r_type_reg_2689 <= d_i_is_r_type_fu_1036_p2;
        d_i_is_store_reg_2663 <= d_i_is_store_fu_992_p2;
        d_i_opcode_reg_2626 <= {{code_ram_q0[6:2]}};
        d_i_rd_reg_2631 <= {{code_ram_q0[11:7]}};
        d_i_rs2_reg_2653 <= {{code_ram_q0[24:20]}};
        d_imm_inst_11_8_reg_2703 <= {{code_ram_q0[11:8]}};
        d_imm_inst_19_12_reg_2637 <= {{code_ram_q0[19:12]}};
        d_imm_inst_31_reg_2697 <= code_ram_q0[32'd31];
        d_imm_inst_7_reg_2708 <= code_ram_q0[32'd7];
        instruction_reg_2613 <= code_ram_q0;
        rv1_reg_2713 <= rv1_fu_1068_p67;
        rv2_reg_2746 <= rv2_fu_1208_p67;
        trunc_ln254_reg_2741 <= trunc_ln254_fu_1204_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        icmp_ln12_reg_2954 <= icmp_ln12_fu_2321_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pc_1_reg_2600 <= pc_fu_270;
    end
end

always @ (posedge ap_clk) begin
    if ((((d_i_is_load_reg_2659 == 1'd1) & (d_i_is_jalr_reg_2667 == 1'd0) & (d_i_type_reg_462 == 3'd2) & (1'b1 == ap_CS_fsm_state4)) | ((d_i_type_reg_462 == 3'd3) & (1'b1 == ap_CS_fsm_state4)))) begin
        reg_645 <= grp_fu_619_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sext_ln175_reg_2931 <= sext_ln175_fu_2017_p1;
        sext_ln179_reg_2941 <= sext_ln179_fu_2033_p1;
        w_reg_2926 <= data_ram_q0;
        zext_ln176_reg_2936[7 : 0] <= zext_ln176_fu_2021_p1[7 : 0];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((d_i_type_reg_462 == 3'd2)) begin
            ap_phi_mux_d_i_imm_5_phi_fu_511_p12 = sext_ln141_fu_1397_p1;
        end else if ((d_i_type_reg_462 == 3'd3)) begin
            ap_phi_mux_d_i_imm_5_phi_fu_511_p12 = sext_ln142_fu_1383_p1;
        end else if ((d_i_type_reg_462 == 3'd4)) begin
            ap_phi_mux_d_i_imm_5_phi_fu_511_p12 = sext_ln143_fu_1362_p1;
        end else if ((d_i_type_reg_462 == 3'd5)) begin
            ap_phi_mux_d_i_imm_5_phi_fu_511_p12 = {{instruction_reg_2613[31:12]}};
        end else if ((d_i_type_reg_462 == 3'd6)) begin
            ap_phi_mux_d_i_imm_5_phi_fu_511_p12 = d_i_imm_fu_1428_p5;
        end else begin
            ap_phi_mux_d_i_imm_5_phi_fu_511_p12 = d_i_imm_5_reg_507;
        end
    end else begin
        ap_phi_mux_d_i_imm_5_phi_fu_511_p12 = d_i_imm_5_reg_507;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd0) & (opch_fu_1016_p4 == 2'd1))) begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 3'd3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd4) & (opch_fu_1016_p4 == 2'd1))) begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 3'd1;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd5) & (opch_fu_1016_p4 == 2'd1)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd5) & (opch_fu_1016_p4 == 2'd0)))) begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 3'd5;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd0) & (opch_fu_1016_p4 == 2'd3))) begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 3'd4;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd1) & (opch_fu_1016_p4 == 2'd3)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd4) & (opch_fu_1016_p4 == 2'd0)) | ((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd0) & (opch_fu_1016_p4 == 2'd0)))) begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 3'd2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (opcl_fu_1026_p4 == 3'd3) & (opch_fu_1016_p4 == 2'd3))) begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 3'd6;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd2)) | (~(opcl_fu_1026_p4 == 3'd3) & ~(opcl_fu_1026_p4 == 3'd1) & ~(opcl_fu_1026_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd3)) | (~(opcl_fu_1026_p4 == 3'd4) & ~(opcl_fu_1026_p4 == 3'd5) & ~(opcl_fu_1026_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd1)) | (~(opcl_fu_1026_p4 == 3'd4) & ~(opcl_fu_1026_p4 == 3'd5) & ~(opcl_fu_1026_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state3) & (opch_fu_1016_p4 == 2'd0)))) begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 3'd7;
    end else begin
        ap_phi_mux_d_i_type_phi_fu_465_p26 = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_pred414_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = result_8_reg_2855;
    end else if (((ap_predicate_pred404_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = result_14_reg_2835;
    end else if (((ap_predicate_pred398_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = result_20_reg_2815;
    end else if (((ap_predicate_pred393_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = result_21_reg_2810;
    end else if (((ap_predicate_pred388_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = zext_ln50_1_fu_1798_p1;
    end else if (((ap_predicate_pred382_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = zext_ln52_1_fu_1794_p1;
    end else if (((ap_predicate_pred373_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = result_27_reg_2790;
    end else if (((d_i_type_reg_462 == 3'd5) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = select_ln100_reg_2775;
    end else if ((((d_i_type_reg_462 == 3'd3) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred66_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = reg_645;
    end else if (((d_i_type_reg_462 == 3'd4) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_result_29_phi_fu_531_p48 = zext_ln97_fu_1790_p1;
    end else begin
        ap_phi_mux_result_29_phi_fu_531_p48 = result_29_reg_527;
    end
end

always @ (*) begin
    if (((d_i_is_load_reg_2659 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_phi_mux_result_34_phi_fu_587_p16 = result_29_reg_527;
    end else if (((d_i_func3_reg_2642 == 3'd0) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_phi_mux_result_34_phi_fu_587_p16 = sext_ln175_reg_2931;
    end else if (((d_i_func3_reg_2642 == 3'd1) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_phi_mux_result_34_phi_fu_587_p16 = sext_ln179_reg_2941;
    end else if (((d_i_func3_reg_2642 == 3'd2) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_phi_mux_result_34_phi_fu_587_p16 = w_reg_2926;
    end else if (((d_i_func3_reg_2642 == 3'd4) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_phi_mux_result_34_phi_fu_587_p16 = zext_ln176_reg_2936;
    end else if ((((d_i_func3_reg_2642 == 3'd3) & (d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state7) & (((d_i_func3_reg_2642 == 3'd6) & (d_i_is_load_reg_2659 == 1'd1)) | ((d_i_func3_reg_2642 == 3'd7) & (d_i_is_load_reg_2659 == 1'd1)))))) begin
        ap_phi_mux_result_34_phi_fu_587_p16 = 32'd0;
    end else begin
        ap_phi_mux_result_34_phi_fu_587_p16 = result_34_reg_584;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        code_ram_ce0 = 1'b1;
    end else begin
        code_ram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_ram_address0 = zext_ln131_3_fu_1918_p1;
    end else if (((d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        data_ram_address0 = zext_ln155_fu_1913_p1;
    end else if (((d_i_is_store_reg_2663 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd0))) begin
        data_ram_address0 = zext_ln128_3_fu_1908_p1;
    end else if (((d_i_is_store_reg_2663 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd2))) begin
        data_ram_address0 = zext_ln134_fu_1821_p1;
    end else begin
        data_ram_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | ((d_i_is_load_reg_2659 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((d_i_is_store_reg_2663 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd0)) | ((d_i_is_store_reg_2663 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd2)))) begin
        data_ram_ce0 = 1'b1;
    end else begin
        data_ram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_ram_d0 = shl_ln131_2_reg_2896;
    end else if (((d_i_is_store_reg_2663 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd0))) begin
        data_ram_d0 = shl_ln128_2_fu_1901_p2;
    end else if (((d_i_is_store_reg_2663 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd2))) begin
        data_ram_d0 = rv2_reg_2746;
    end else begin
        data_ram_d0 = 'bx;
    end
end

always @ (*) begin
    if ((d_i_is_store_reg_2663 == 1'd1)) begin
        if (((1'b1 == ap_CS_fsm_state6) & (msize_reg_2877 == 2'd1))) begin
            data_ram_we0 = shl_ln131_reg_2891;
        end else if (((1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd0))) begin
            data_ram_we0 = shl_ln128_fu_1882_p2;
        end else if (((1'b1 == ap_CS_fsm_state5) & (msize_fu_1806_p4 == 2'd2))) begin
            data_ram_we0 = 4'd15;
        end else begin
            data_ram_we0 = 4'd0;
        end
    end else begin
        data_ram_we0 = 4'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        nb_instruction_ap_vld = 1'b1;
    end else begin
        nb_instruction_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((or_ln12_fu_2332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a01_fu_1802_p1 = ap_phi_mux_result_29_phi_fu_531_p48[1:0];

assign a1_1_fu_1922_p3 = result_29_reg_527[32'd1];

assign add_ln224_fu_2285_p2 = (trunc_ln254_reg_2741 + trunc_ln74_reg_2765);

assign add_ln233_fu_2270_p2 = (select_ln264_fu_2262_p3 + pc_1_reg_2600);

assign add_ln239_fu_2237_p2 = (trunc_ln6_fu_2227_p4 + pc_1_reg_2600);

assign add_ln36_fu_2340_p2 = (nbi_fu_266 + 32'd1);

assign and_ln18_fu_1609_p2 = (icmp_ln18_6_fu_1604_p2 & icmp_ln18_5_fu_1599_p2);

assign and_ln205_fu_2057_p2 = (icmp_ln205_fu_2041_p2 & icmp_ln205_1_fu_2051_p2);

assign and_ln43_1_fu_1682_p2 = (grp_fu_623_p3 & d_i_is_r_type_reg_2689);

assign and_ln43_fu_1765_p2 = (grp_fu_623_p3 & d_i_is_r_type_reg_2689);

assign and_ln_fu_1838_p3 = {{tmp_6_fu_1830_p3}, {1'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign b0_fu_1930_p1 = data_ram_q0[7:0];

assign b1_fu_1934_p4 = {{data_ram_q0[15:8]}};

assign b2_fu_1948_p4 = {{data_ram_q0[23:16]}};

assign b3_fu_1958_p4 = {{data_ram_q0[31:24]}};

assign b_4_fu_1983_p3 = ((icmp_ln168_fu_1978_p2[0:0] == 1'b1) ? b2_fu_1948_p4 : b3_fu_1958_p4);

assign b_5_fu_1996_p3 = ((icmp_ln168_1_fu_1991_p2[0:0] == 1'b1) ? b1_fu_1934_p4 : b_4_fu_1983_p3);

assign b_fu_2009_p3 = ((icmp_ln168_2_fu_2004_p2[0:0] == 1'b1) ? b0_fu_1930_p1 : b_5_fu_1996_p3);

assign code_ram_address0 = zext_ln12_fu_825_p1;

assign cond_fu_2223_p1 = ap_phi_mux_result_34_phi_fu_587_p16[0:0];

assign d_i_imm_2_fu_1388_p4 = {{instruction_reg_2613[31:20]}};

assign d_i_imm_3_fu_1376_p3 = {{tmp_2_fu_1367_p4}, {d_i_rd_reg_2631}};

assign d_i_imm_4_fu_1353_p5 = {{{{d_imm_inst_31_reg_2697}, {d_imm_inst_7_reg_2708}}, {tmp_4_fu_1344_p4}}, {d_imm_inst_11_8_reg_2703}};

assign d_i_imm_fu_1428_p5 = {{{{d_imm_inst_31_reg_2697}, {d_imm_inst_19_12_reg_2637}}, {tmp_fu_1412_p3}}, {tmp_1_fu_1419_p4}};

assign d_i_is_jalr_fu_998_p2 = ((d_i_opcode_fu_926_p4 == 5'd25) ? 1'b1 : 1'b0);

assign d_i_is_load_fu_986_p2 = ((d_i_opcode_fu_926_p4 == 5'd0) ? 1'b1 : 1'b0);

assign d_i_is_lui_fu_1004_p2 = ((d_i_opcode_fu_926_p4 == 5'd13) ? 1'b1 : 1'b0);

assign d_i_is_op_imm_fu_1010_p2 = ((d_i_opcode_fu_926_p4 == 5'd4) ? 1'b1 : 1'b0);

assign d_i_is_r_type_fu_1036_p2 = ((ap_phi_mux_d_i_type_phi_fu_465_p26 == 3'd1) ? 1'b1 : 1'b0);

assign d_i_is_store_fu_992_p2 = ((d_i_opcode_fu_926_p4 == 5'd8) ? 1'b1 : 1'b0);

assign d_i_opcode_fu_926_p4 = {{code_ram_q0[6:2]}};

assign grp_fu_611_p2 = ((rv1_reg_2713 < rv2_reg_2746) ? 1'b1 : 1'b0);

assign grp_fu_615_p2 = (($signed(rv1_reg_2713) < $signed(rv2_reg_2746)) ? 1'b1 : 1'b0);

assign grp_fu_619_p2 = ($signed(rv1_reg_2713) + $signed(sext_ln74_fu_1439_p1));

assign grp_fu_623_p3 = instruction_reg_2613[32'd30];

assign grp_fu_630_p4 = {{ap_phi_mux_result_29_phi_fu_531_p48[17:2]}};

assign grp_fu_640_p2 = (pc_1_reg_2600 + 16'd1);

assign h0_fu_1944_p1 = data_ram_q0[15:0];

assign h1_fu_1968_p4 = {{data_ram_q0[31:16]}};

assign h_fu_2025_p3 = ((a1_1_fu_1922_p3[0:0] == 1'b1) ? h1_fu_1968_p4 : h0_fu_1944_p1);

assign icmp_ln12_1_fu_2326_p2 = ((pc_fu_270 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_2321_p2 = ((instruction_reg_2613 != 32'd32871) ? 1'b1 : 1'b0);

assign icmp_ln168_1_fu_1991_p2 = ((a01_reg_2870 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln168_2_fu_2004_p2 = ((a01_reg_2870 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_1978_p2 = ((a01_reg_2870 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln18_1_fu_1521_p2 = ((d_i_func3_reg_2642 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_1526_p2 = ((d_i_func3_reg_2642 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln18_3_fu_1531_p2 = ((d_i_func3_reg_2642 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln18_4_fu_1536_p2 = ((d_i_func3_reg_2642 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_5_fu_1599_p2 = ((d_i_func3_reg_2642 != 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln18_6_fu_1604_p2 = ((d_i_func3_reg_2642 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_1516_p2 = ((d_i_func3_reg_2642 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_1494_p2 = ((rv1_reg_2713 == rv2_reg_2746) ? 1'b1 : 1'b0);

assign icmp_ln205_1_fu_2051_p2 = ((or_ln205_fu_2046_p2 != 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_2041_p2 = ((d_i_rd_reg_2631 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_1498_p2 = ((rv1_reg_2713 != rv2_reg_2746) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_1502_p2 = (($signed(rv1_reg_2713) < $signed(rv2_reg_2746)) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_1512_p2 = ((rv1_reg_2713 < rv2_reg_2746) ? 1'b1 : 1'b0);

assign imm12_fu_1448_p3 = {{ap_phi_mux_d_i_imm_5_phi_fu_511_p12}, {12'd0}};

assign msize_fu_1806_p4 = {{instruction_reg_2613[13:12]}};

assign npc4_fu_1465_p2 = (pc4_fu_1456_p2 + 16'd4);

assign opch_fu_1016_p4 = {{code_ram_q0[6:5]}};

assign opcl_fu_1026_p4 = {{code_ram_q0[4:2]}};

assign or_ln12_fu_2332_p2 = (icmp_ln12_reg_2954 | icmp_ln12_1_fu_2326_p2);

assign or_ln18_1_fu_1563_p2 = (icmp_ln18_2_fu_1526_p2 | icmp_ln18_1_fu_1521_p2);

assign or_ln18_2_fu_1585_p2 = (or_ln18_fu_1549_p2 | or_ln18_1_fu_1563_p2);

assign or_ln18_fu_1549_p2 = (icmp_ln18_4_fu_1536_p2 | icmp_ln18_3_fu_1531_p2);

assign or_ln205_fu_2046_p2 = (d_i_opcode_reg_2626 | 5'd16);

assign pc4_fu_1456_p2 = pc_1_reg_2600 << 16'd2;

assign result_11_fu_1744_p2 = (rv2_reg_2746 ^ rv1_reg_2713);

assign result_12_fu_1726_p2 = $signed(rv1_reg_2713) >>> zext_ln57_fu_1722_p1;

assign result_13_fu_1731_p2 = rv1_reg_2713 >> zext_ln57_fu_1722_p1;

assign result_14_fu_1736_p3 = ((grp_fu_623_p3[0:0] == 1'b1) ? result_12_fu_1726_p2 : result_13_fu_1731_p2);

assign result_15_fu_1718_p2 = (rv2_reg_2746 | rv1_reg_2713);

assign result_17_fu_1700_p2 = (sext_ln74_fu_1439_p1 & rv1_reg_2713);

assign result_18_fu_1687_p2 = ($signed(rv1_reg_2713) - $signed(sext_ln74_fu_1439_p1));

assign result_1_fu_1615_p2 = (select_ln18_4_fu_1591_p3 & and_ln18_fu_1609_p2);

assign result_20_fu_1692_p3 = ((and_ln43_1_fu_1682_p2[0:0] == 1'b1) ? result_18_fu_1687_p2 : grp_fu_619_p2);

assign result_21_fu_1677_p2 = rv1_reg_2713 << zext_ln48_1_fu_1673_p1;

assign result_22_fu_1668_p2 = (($signed(rv1_reg_2713) < $signed(sext_ln74_fu_1439_p1)) ? 1'b1 : 1'b0);

assign result_23_fu_1663_p2 = ((rv1_reg_2713 < sext_ln74_fu_1439_p1) ? 1'b1 : 1'b0);

assign result_24_fu_1658_p2 = (sext_ln74_fu_1439_p1 ^ rv1_reg_2713);

assign result_25_fu_1640_p2 = $signed(rv1_reg_2713) >>> zext_ln57_1_fu_1636_p1;

assign result_26_fu_1645_p2 = rv1_reg_2713 >> zext_ln57_1_fu_1636_p1;

assign result_27_fu_1650_p3 = ((grp_fu_623_p3[0:0] == 1'b1) ? result_25_fu_1640_p2 : result_26_fu_1645_p2);

assign result_28_fu_1631_p2 = (sext_ln74_fu_1439_p1 | rv1_reg_2713);

assign result_2_fu_1475_p2 = (imm12_fu_1448_p3 + zext_ln103_fu_1461_p1);

assign result_4_fu_1786_p2 = (rv2_reg_2746 & rv1_reg_2713);

assign result_5_fu_1770_p2 = (rv1_reg_2713 - rv2_reg_2746);

assign result_6_fu_1774_p2 = (rv2_reg_2746 + rv1_reg_2713);

assign result_7_fu_1778_p3 = ((and_ln43_fu_1765_p2[0:0] == 1'b1) ? result_5_fu_1770_p2 : result_6_fu_1774_p2);

assign result_8_fu_1760_p2 = rv1_reg_2713 << zext_ln48_fu_1756_p1;

assign rv1_fu_1068_p65 = 'bx;

assign rv1_fu_1068_p66 = {{code_ram_q0[19:15]}};

assign rv2_01_fu_1818_p1 = rv2_reg_2746[15:0];

assign rv2_0_fu_1815_p1 = rv2_reg_2746[7:0];

assign rv2_fu_1208_p65 = 'bx;

assign rv2_fu_1208_p66 = {{code_ram_q0[24:20]}};

assign select_ln100_fu_1481_p3 = ((d_i_is_lui_reg_2672[0:0] == 1'b1) ? imm12_fu_1448_p3 : result_2_fu_1475_p2);

assign select_ln18_1_fu_1555_p3 = ((icmp_ln18_2_fu_1526_p2[0:0] == 1'b1) ? grp_fu_615_p2 : xor_ln24_fu_1506_p2);

assign select_ln18_2_fu_1569_p3 = ((icmp_ln18_fu_1516_p2[0:0] == 1'b1) ? icmp_ln25_fu_1512_p2 : xor_ln26_fu_1488_p2);

assign select_ln18_3_fu_1577_p3 = ((or_ln18_fu_1549_p2[0:0] == 1'b1) ? select_ln18_fu_1541_p3 : select_ln18_1_fu_1555_p3);

assign select_ln18_4_fu_1591_p3 = ((or_ln18_2_fu_1585_p2[0:0] == 1'b1) ? select_ln18_3_fu_1577_p3 : select_ln18_2_fu_1569_p3);

assign select_ln18_fu_1541_p3 = ((icmp_ln18_4_fu_1536_p2[0:0] == 1'b1) ? icmp_ln19_fu_1494_p2 : icmp_ln20_fu_1498_p2);

assign select_ln222_fu_2299_p3 = ((d_i_is_jalr_reg_2667[0:0] == 1'b1) ? trunc_ln4_fu_2289_p4 : grp_fu_640_p2);

assign select_ln264_fu_2262_p3 = ((cond_fu_2223_p1[0:0] == 1'b1) ? trunc_ln5_fu_2252_p4 : 16'd1);

assign sext_ln141_fu_1397_p1 = $signed(d_i_imm_2_fu_1388_p4);

assign sext_ln142_fu_1383_p1 = $signed(d_i_imm_3_fu_1376_p3);

assign sext_ln143_fu_1362_p1 = $signed(d_i_imm_4_fu_1353_p5);

assign sext_ln175_fu_2017_p1 = b_fu_2009_p3;

assign sext_ln179_fu_2033_p1 = h_fu_2025_p3;

assign sext_ln74_fu_1439_p1 = ap_phi_mux_d_i_imm_5_phi_fu_511_p12;

assign shift_1_fu_1712_p3 = ((d_i_is_r_type_reg_2689[0:0] == 1'b1) ? shift_fu_1709_p1 : d_i_rs2_reg_2653);

assign shift_2_fu_1621_p1 = ap_phi_mux_d_i_imm_5_phi_fu_511_p12[4:0];

assign shift_3_fu_1625_p3 = ((d_i_is_r_type_reg_2689[0:0] == 1'b1) ? shift_2_fu_1621_p1 : d_i_rs2_reg_2653);

assign shift_fu_1709_p1 = rv2_reg_2746[4:0];

assign shl_ln128_1_fu_1889_p3 = {{a01_fu_1802_p1}, {3'd0}};

assign shl_ln128_2_fu_1901_p2 = zext_ln128_fu_1874_p1 << zext_ln128_2_fu_1897_p1;

assign shl_ln128_fu_1882_p2 = 4'd1 << zext_ln128_1_fu_1878_p1;

assign shl_ln131_1_fu_1856_p3 = {{tmp_6_fu_1830_p3}, {4'd0}};

assign shl_ln131_2_fu_1868_p2 = zext_ln131_fu_1826_p1 << zext_ln131_2_fu_1864_p1;

assign shl_ln131_fu_1850_p2 = 4'd3 << zext_ln131_1_fu_1846_p1;

assign tmp_1_fu_1419_p4 = {{instruction_reg_2613[30:21]}};

assign tmp_2_fu_1367_p4 = {{instruction_reg_2613[31:25]}};

assign tmp_4_fu_1344_p4 = {{instruction_reg_2613[30:25]}};

assign tmp_6_fu_1830_p3 = ap_phi_mux_result_29_phi_fu_531_p48[32'd1];

assign tmp_fu_1412_p3 = instruction_reg_2613[32'd20];

assign trunc_ln254_fu_1204_p1 = rv1_fu_1068_p67[17:0];

assign trunc_ln39_fu_651_p1 = start_pc[15:0];

assign trunc_ln4_fu_2289_p4 = {{add_ln224_fu_2285_p2[17:2]}};

assign trunc_ln5_fu_2252_p4 = {{d_i_imm_5_reg_507[16:1]}};

assign trunc_ln6_fu_2227_p4 = {{d_i_imm_5_reg_507[16:1]}};

assign trunc_ln74_fu_1444_p1 = ap_phi_mux_d_i_imm_5_phi_fu_511_p12[17:0];

assign xor_ln24_fu_1506_p2 = (icmp_ln24_fu_1502_p2 ^ 1'd1);

assign xor_ln26_fu_1488_p2 = (grp_fu_611_p2 ^ 1'd1);

assign zext_ln103_fu_1461_p1 = pc4_fu_1456_p2;

assign zext_ln106_fu_1471_p1 = npc4_fu_1465_p2;

assign zext_ln128_1_fu_1878_p1 = a01_fu_1802_p1;

assign zext_ln128_2_fu_1897_p1 = shl_ln128_1_fu_1889_p3;

assign zext_ln128_3_fu_1908_p1 = grp_fu_630_p4;

assign zext_ln128_fu_1874_p1 = rv2_0_fu_1815_p1;

assign zext_ln12_fu_825_p1 = pc_fu_270;

assign zext_ln131_1_fu_1846_p1 = and_ln_fu_1838_p3;

assign zext_ln131_2_fu_1864_p1 = shl_ln131_1_fu_1856_p3;

assign zext_ln131_3_fu_1918_p1 = a1_reg_2881;

assign zext_ln131_fu_1826_p1 = rv2_01_fu_1818_p1;

assign zext_ln134_fu_1821_p1 = grp_fu_630_p4;

assign zext_ln155_fu_1913_p1 = grp_fu_630_p4;

assign zext_ln176_fu_2021_p1 = $unsigned(b_fu_2009_p3);

assign zext_ln180_fu_2037_p1 = $unsigned(h_fu_2025_p3);

assign zext_ln48_1_fu_1673_p1 = shift_3_fu_1625_p3;

assign zext_ln48_fu_1756_p1 = shift_1_fu_1712_p3;

assign zext_ln50_1_fu_1798_p1 = result_22_reg_2805;

assign zext_ln50_fu_1752_p1 = grp_fu_615_p2;

assign zext_ln52_1_fu_1794_p1 = result_23_reg_2800;

assign zext_ln52_fu_1748_p1 = grp_fu_611_p2;

assign zext_ln57_1_fu_1636_p1 = shift_3_fu_1625_p3;

assign zext_ln57_fu_1722_p1 = shift_1_fu_1712_p3;

assign zext_ln84_fu_1705_p1 = npc4_fu_1465_p2;

assign zext_ln97_fu_1790_p1 = result_1_reg_2780;

always @ (posedge ap_clk) begin
    select_ln100_reg_2775[1:0] <= 2'b00;
    zext_ln176_reg_2936[31:8] <= 24'b000000000000000000000000;
end

endmodule //rv32i_npp_ip
