// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fetching_decoding_ip_statistic_update (
        ap_ready,
        nbi_read,
        ap_return
);


output   ap_ready;
input  [31:0] nbi_read;
output  [31:0] ap_return;

assign ap_ready = 1'b1;

assign ap_return = (nbi_read + 32'd1);

endmodule //fetching_decoding_ip_statistic_update
