// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fetching_ip_execute (
        ap_ready,
        pc_val,
        ap_return
);


output   ap_ready;
input  [15:0] pc_val;
output  [15:0] ap_return;

assign ap_ready = 1'b1;

assign ap_return = (pc_val + 16'd1);

endmodule //fetching_ip_execute
