
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xfetching_ip.h"

/*
* The configuration table for devices
*/

XFetching_ip_Config XFetching_ip_ConfigTable[XPAR_XFETCHING_IP_NUM_INSTANCES] =
{
	{
		XPAR_FETCHING_IP_0_DEVICE_ID,
		XPAR_FETCHING_IP_0_S_AXI_CONTROL_BASEADDR
	}
};


