domain_path: C:\Users\monde\Documents\GitHub\nasa-CPU\Vitis_workspace\platform_rv32i_npp_ip\export\platform_rv32i_npp_ip\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
