// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fde_ip_running_cond_update (
        ap_ready,
        instruction,
        pc_val,
        ap_return
);


output   ap_ready;
input  [31:0] instruction;
input  [15:0] pc_val;
output  [0:0] ap_return;

wire   [0:0] icmp_ln21_fu_24_p2;
wire   [0:0] icmp_ln21_1_fu_30_p2;

assign ap_ready = 1'b1;

assign ap_return = (icmp_ln21_fu_24_p2 | icmp_ln21_1_fu_30_p2);

assign icmp_ln21_1_fu_30_p2 = ((instruction != 32'd32871) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_24_p2 = ((pc_val != 16'd0) ? 1'b1 : 1'b0);

endmodule //fde_ip_running_cond_update
